### ISSUE TITLE
Incorrect behaviour with KnockoutJS  (OSX, iOS)

### ISSUE THREAD

**Issue by angelpcadena** [RobinHerbots/Inputmask#1382] opened 2016-09-08 20:21 UTC
Hello, I made an unobtrusive knockout binding for jquery.inputMask, that is, the plugin doesn't try to modify the observable directly.

autoUnmask is set to true, so the actual value in the input is not decorated, and the observable is also not decorated, this is the expected behavior.

But in Safari (OSX and iOS) and Chrome (iOS) this is not working, I made a fiddle to demonstrate the error.

[jsFiddle](https://jsfiddle.net/SrGoodbar/Lh4oan07/)

OSX version is 10.11
iOS version is 9.3.4

**Comment by RobinHerbots** [comment] 2016-09-09 07:43
@angelpcadena , 

First guess is that the value property patching is not working in osx and that the mask is falling back to using jQuery.val.  Which means that changes by the observable are not detected.

Writing an extender which trigger the "setvalue" event would be a possible fix for this.  (I never used knockout, so I can be wrong)

Something like

```
ko.extenders.inputmask_setvalue = function(target, option) {
    if (target.inputmask.__valueGet === undefined) {   //assuming that the target is a ref to the dom-element
         $(target).trigger("setvalue");
    }
    return target;
};

...
self.amount = ko.observable(5000).extend({ inputmask_setvalue });

```

**Comment by angelpcadena** [comment] 2016-09-09 15:52
Thanks for your reply.

The extender you proposed can't work as it is, since Knockout observables don't keep a reference to the DOM elements they are binded to (if any) only the bindings have that information.

I'm making some tests to see if I can manage some workaround using the $.trigger('setValue') in my custom binding.

edit: Here's what I have for a workaround so far, I didn't want to meddle with the observables but oh well

[jsFiddle](https://jsfiddle.net/SrGoodbar/4r4bccqh/)

Still pending is making the two-way binding work correctly.

**Comment by RobinHerbots** [comment] 2016-09-12 07:12
@angelpcadena , 

Some users have contributed some docs in the wiki pages about knockout & the inputmask

**Comment by angelpcadena** [comment] 2016-09-12 07:31
@RobinHerbots 

Yes, we had a custom binding as stated in the wiki, however, I think that with inputMask in particular, assigning to the observables directly brings more issues in the KnockoutJS lifecycle, especially using the validation library.

Anyways, I know that KnockoutJS support is not guaranteed with this plugin, but I believe there's an issue on webkit on iOS and Safari on OSX, do you think it's a browser bug? Is there something to do on the plugin's end?

**Comment by RobinHerbots** [comment] 2016-09-12 07:50
@angelpcadena , 

I already mentioned the reason in previous comments..  It is not a bug but a lack of support for patching internal properties.  (value property)  

Feel free to add your comments into the wiki,

I will add an developer options to disable the value patching.  That makes it easier to test this.

**Comment by RobinHerbots** [comment] 2016-09-12 07:58
@angelpcadena , 

Can you put the following opriotn to the inputmask.  noValuePatching: true and use the inputmask.js from github (js folder)  And test the same again but in Chrome.  Do you have now the same behavior as in safari in osx?

**Comment by angelpcadena** [comment] 2016-09-12 14:45
@RobinHerbots ,

I made a fiddle with the js file you mentioned, noValuePatching: true makes inputMask behave like on safari OSX in all places, so that must be it.

[jsFiddle](https://jsfiddle.net/SrGoodbar/g6deradr/)

To bad about the lack of support for value patching on apple's end.

Gonna see if I can make a cleaner workaround, this is a great plugin!

**Comment by futpib** [comment] 2017-04-18 12:04
Oh nice, we have `noValuePatching` option now \o/. I encountered basically the same issue with Safari and proposed similar option in #1276 and that worked well as a workaround for me.

**Comment by RobinHerbots** [comment] 2017-04-19 13:16
@futpib , 

It is still a dev option, ... but I will upgrade it's status to a true option!  ( just for you)  ;-)

**Closed as completed by RobinHerbots** 2017-04-19 13:16 UTC
Labels: Main, Life example included => priority
