### ISSUE TITLE
For 'decimal' or 'numeric' alias, how to show blank for zero values?

### ISSUE THREAD

**Issue by Guy--L** [RobinHerbots/Inputmask#891] opened 2015-04-24 05:20 UTC
This seems like a simple thing.  When the input has a zero value, show nothing in the input.  But I cannot find how to do this.  0 => ''.  This is a request for initial values as retrieved from the http response.

Do you have a way?  (I saw a prior issue requesting this; but the answer did not address the issue directly.)

**Comment by RobinHerbots** [comment] 2015-05-04 12:16
duplicate of #786

**Closed as completed by RobinHerbots** 2015-05-04 12:16 UTC
Labels: Numerics
