### ISSUE TITLE
'0' getting added unnecessarily if navigating using arrow key for datetime input mask

### ISSUE THREAD

**Issue by harshal-ringe** [RobinHerbots/Inputmask#2289] opened 2020-03-09 11:10 UTC
- Go to https://robinherbots.github.io/Inputmask/ .  Go to Demo Section. Click inside date input. navigate to the right side using the right arrow key. If you press any number, 0 gets appended initially at month/date.
- Check below screenshot
https://nimbus-screenshots.s3.amazonaws.com/s/fca06660078bf29ed3f215ee616caf3b.png 
https://nimbus-screenshots.s3.amazonaws.com/s/ebfa0bd50231d25de753ba6792a66ac3.png
- OS: Ubuntu 16.04
- Browser: Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- Inputmask version: jquery.inputmask 5.0.4-beta.32

**Comment by harshal-ringe** [comment] 2020-03-13 13:37
Hi @RobinHerbots,  Is there any workaround to resolve this issue?

**Comment by RobinHerbots** [comment] 2020-03-13 13:41
@harshal247software , 

I know why it happens, but I haven't found the time to look for a solution to this.

**Comment by Seva42matters** [comment] 2020-05-07 21:56
Hi there,

any ideas about how this could be fixed? Thx

**Comment by jackiems82** [comment] 2020-11-19 08:33
Basically the same issue appears also when you have a valid date in the input but want to change something.

**Example (experienced in the demo page):** 

- Enter 11/30/2020 an click outside of the input _(mm/dd/yyy format)_
- Click on the 3 inside and enter 29
- it will end up like this: 11/02/9020

Don't know if this is worth another bug but it feels like being the same problem. Otherwise please advise.

Any indication when anyone could have time to implement a fix?

**Comment by RobinHerbots** [comment] 2020-12-01 21:14
@harshal247software,

The issue is fixed in the latest beta version 5.0.6-beta.21.

@jackiems82,
I created a new issue for this

**Closed as completed by RobinHerbots** 2020-12-01 21:14 UTC
Labels: Dates, Main, Enhancement / Feature
