### ISSUE TITLE
Troubles with phone mask

### ISSUE THREAD

**Issue by hotleadru** [RobinHerbots/Inputmask#1378] opened 2016-09-06 04:14 UTC
Hi. 

Have a troubles with different masks in once countries.

49 (Germany) doesn't work. After typing 49, ( appears with no ending ).
52 (Mexico) doesn't work. After typing 52, I can't type more digits.
84 (Vietnam) doesn't work. After typing 84, I can't type more digits.
86 (China) doesn't work. After typing 49, ( appears with no ending ).
592 (Guyana) adds an extra 2 after typing 592, and I can't type more digits.
598 (Uruguay) adds an extra 8 after typing 598, and I can't type more digits.

When you fill phone from Germany http://prntscr.com/cenqe8 it's get only one mask but in the JS we have many masks http://prntscr.com/cenr1b
And when you delete { "mask": "+49-###-###", "cc": "DE", "cd": "Germany", "desc_en": "", "name_ru": "Германия", "desc_ru": "" }, It's start showing other masks.

**Comment by RobinHerbots** [comment] 2016-09-06 08:05
#970

**Comment by ghost** [comment] 2017-10-31 13:05
Hi Robin!

We actively use your mask and encounter a similar problem. It's very important for us. Can we hope for the correction of this bug in the near feature?

**Comment by RobinHerbots** [comment] 2017-10-31 13:41
@vm-dezertir , 
Do you also use the phone alias?  Or is this for a custom alternation?

Currently I don't have much spare time available, so I really need to block time to be able to work on this.
It helps if you create a jsfiddle and give as much info as possible.

**Comment by ghost** [comment] 2017-10-31 14:47
Yep, we used you phone alias. We didn't add anything custom options (basics masks - fully satisfy us). Our problem -with phones from Germany. We can't write valid phone number like this --> https://screenshare.ru/LodBZBvp . In phone.js - we have this mask.
We understand that you busy. So, if you can give us the cue - we try to fix this bug.

**Comment by RobinHerbots** [comment] 2017-11-05 07:47
@vm-dezertir , @hotleadru ,

Can you have a try with the current 4.x branch.  I pushed an update yesterday.

**Comment by ghost** [comment] 2017-11-05 19:39
Great!). I will look and write result

**Comment by ghost** [comment] 2017-11-06 08:37
Unfortunately, the same trouble

**Comment by RobinHerbots** [comment] 2017-11-06 09:01
@vm-dezertir , 

Can you describe the trouble a bit.  What exactly goes wrong.  Create a jsfiddle with some examples.  Describe the behavior and expected behavior.

**Comment by sphereagency** [comment] 2017-12-08 09:18
Hi Robin,
As described in previous posts Germany is a problem.
In fact if you type the number +49(177)123-4567 in your demo page you will get an incomplete mask. It should normally match the second mask **mask:"+49(###)###-####"** but it seems that when you are typing the number, you jump from third mask  **+49(###)##-####** to first mask **+49(####)###-####**
In fact the 4th and 5th masks never get matched when you type (you jump from initial 7th mask to 3rd)

This behaviour occurs on your demo site and in my implementations.

Thanks a lot for your help

**Comment by RobinHerbots** [comment] 2018-01-11 00:41
@sphereagency , @vm-dezertir , @hotleadru ,

The current version 4.x on github can handle the german phone.  There is still some issue when typing more chars then the longest mask available, but that will be fixed tomorrow.

**Comment by sphereagency** [comment] 2018-01-11 08:11
Thanks, I will try that right now and tell you if ok :)

**Comment by sphereagency** [comment] 2018-01-12 09:02
Hi, seems to work really better than before :) A few things though:

For Italy, you should replace the single mask type definition by;

{mask:"+39(0##)####-##-##",cc:"IT",cd:"Italy",desc_en:""},{mask:"+39(0##)####-###",cc:"IT",cd:"Italy",desc_en:""},{mask:"+39(0##)###-###",cc:"IT",cd:"Italy",desc_en:""},{mask:"+39(0##)##-###",cc:"IT",cd:"Italy",desc_en:""},{mask:"+39(0##)##-##",cc:"IT",cd:"Italy",desc_en:""},{mask:"+39(0#)##-##",cc:"IT",cd:"Italy",desc_en:""},{mask:"+39(3##)###-##-##",cc:"IT",cd:"Italy",desc_en:""},{mask:"+39(3##)##-##-##",cc:"IT",cd:"Italy",desc_en:""}

Because there can be 6 to 11 numbers depending on the first number (0 + [0-9]{6,11} for landline or 3 + [0-9]{9,10} for mobiles)

Number for the US and CA (+1...) don't return the correct occurrence so you can't get the country name or code while typing. It even return a null object in many case although the mask still works because its the same size of mask for all number + the country code for the default number is an array and not a string which gives extra headache to parse (['us','ca'] :)

For the rest, I'll keep debugging and tell you when its ok or not

**Comment by ghost** [comment] 2018-01-12 09:17
Thanks, Germany phone work fine). Good job!
P.S. We will sent you beer money

**Comment by sphereagency** [comment] 2018-01-12 09:51
:) Thank you even if I prefer vodka that will be fine.

**Comment by RobinHerbots** [comment] 2018-01-12 10:53
@vm-dezertir , @sphereagency , 

Maybe a cocktail with vodka & beer ;-)

**Comment by sphereagency** [comment] 2018-01-15 10:14
Hi, 
Here is a new thing I noticed with Version: 4.0.0-89
You have to replace for INDONESIA the current mask set with this one:

{mask:"+62(8##)###-###",cc:"ID",cd:"Indonesia ",desc_en:"mobile"},
{mask:"+62(8##)###-####",cc:"ID",cd:"Indonesia ",desc_en:"mobile"},
{mask:"+62(8##)###-##-###",cc:"ID",cd:"Indonesia ",desc_en:"mobile"},
{mask:"+62(##)###-##",cc:"ID",cd:"Indonesia",desc_en:""},
{mask:"+62(##)###-###",cc:"ID",cd:"Indonesia",desc_en:""},
{mask:"+62(##)###-####",cc:"ID",cd:"Indonesia",desc_en:""}

Seems that:
- you set was not in the correct order
- the mask function cannot handle a mix of - and ( separators at the first place after prefix.

**Comment by ghost** [comment] 2018-01-16 13:22
Hi Robin!
When you planed merge the current version 4.x  with stable?

**Comment by RobinHerbots** [comment] 2018-01-18 16:28
@sphereagency , 

The order of the masks shouldn't make a difference as they get reordered at runtime.  I will test your extra cases, as soon I think the inputmask is stable enough. 

@vm-dezertir , 
Version 4.x will be the new stable.  I will not merge the changes back to 3.x.

**Comment by sphereagency** [comment] 2018-01-19 09:46
Hi Robin,
A debug on Finlandia phone numbers. The current mask doesn't fit all.
Numbers there can be of a variable length (zone prefix 1 or 2 digits + 4 > 10 digits)

Here are the rules that are allowed: (all prefixed with +358)

+358 13 [0-9]{4-10}
+358 14 [0-9]{5-10}
+358 15 [0-9]{4-10}
+358 16 [0-9]{4-10}
+358 17 [0-9]{5-10}
+358 18 [0-9]{4-8}
+358 19 [0-9]{4-10}

+358 20 [0-9]{4-8}
+358 2 [0-9]{4-10}
+358 3 [0-9]{4-10}
+358 50 [0-9]{4-8}
+358 5 [0-9]{4-10}

+358 601 [0-9]{5-6}
+358 602 [0-9]{5-6}
+358 606 [0-9]{7}
+358 6 [0-9]{4-10}

+358 8 [0-9]{4-10}
+358 9 [0-9]{4-10}

That would lead to many rules using your mask format except if we can add an optionnal char mask symbol like:

{mask:"+358(13)####??????",cc:"FI",cd:"Finlandia",desc_en:""}

... my 2 cents... for now I have extended the mask to allow 5 to 12 digits

**Comment by RobinHerbots** [comment] 2018-01-19 10:03
@sphereagency , 

Optionals are marked with []
+358(13)####[######]
But this one is better:
+358(13)#{4,10}

The phone.js file & format comes from another project.  Inputmask-multi.  Maybe it is time to review and adapt the format.  The # is not needed and can be left 9.  Also more masks can be consolidated into one when using the posibilities of repeats and options in the mask definition.  Or should we use regex as the format for the masks?

Maybe also create a phone-fi.js ?

**Comment by sphereagency** [comment] 2018-01-19 12:09
Hi Robin. 
I believe it should really be lightened in fact. If the regex usage works, I believe its more 'programmatically' friendly even if less readable.

One thing you should do is remove the dash and or () formatting for a number and just leave a space before and after the regional code. that would transform xxx-xxx and xx-xx-xx into xxxxxx. It might also help in case of copy paste.

The real problem is the size of the file you have to parse. It causes performance issues. Having multiple files is not quite easy to use because you have to implement each load of definition file in the plugin.

Have you considered integrating https://github.com/googlei18n/libphonenumber/tree/master/javascript
into your plugin ? Its quite lightweight. Compiled js is 236kb

check simple integration there: http://preview.sphereagency.be/debug/test.htm

It has all definitions for regional exceptions like the on in finland.

**Comment by ghost** [comment] 2018-01-19 13:04
When will planned release 4x?

**Comment by sphereagency** [comment] 2018-01-25 08:47
Hi Robin,
Hope you are ok. I have updated the IE mask to 

{mask:"+353(##)####[####]",cc:"IE",cd:"Ireland",desc_en:""},

to reflect the real number plan possibilities (area code 1>3 digits and subscriber number 5 to 7 digits)

Did you decide something about the rules rewriting ? Maybe I can help writing regulars if you decide to keep your structure.

For example for Ireland could we write something like

+353(1|[2456789]{1}[1-9]{1}|402|404)#{5,7}

which would mean that area code could be
1
21>29, 31>39, .... 91>99
402
404

followed by 5 to 7 digits which could be written #{5,7} or #{3} #{2,4} to introduce a space a give more readability.

In fact Ireland should have more complicated rules (no 48 or 72, 73 75>79, and no 92 area code for example)

Tell me what you think :)

Thanks

**Comment by RobinHerbots** [comment] 2018-01-25 09:09
@sphereagency , 

Replacing all the phone codes will require a lot of work.  I first want to release v4.0.  It would be nice if the libphonenumber lib can provide maskdefinitions to use with inputmask.  

I don't have much time currently to investigate the possibilities.  Both in the direction of integrating with libphonenumber as rewriting the masks.  Feel free to send some PR ;-)

**Comment by RobinHerbots** [comment] 2018-08-28 09:52
Create new phone alias based on libphonenumber #1982

Remove Phone alias #1981

**Closed as completed by RobinHerbots** 2018-08-28 09:52 UTC
Labels: Main, Phone, Multi & Alternation, Enhancement / Feature
