### ISSUE TITLE
On Android with date mask input mashing up

### ISSUE THREAD

**Issue by unbreak** [RobinHerbots/Inputmask#1708] opened 2017-10-03 11:48 UTC
When day typed and start typing month numbers mashing up:
https://jsfiddle.net/cp3cunm0/9/

When i try type: 13061985 ive got: 13/01/2050

**Comment by kwadrax** [comment] 2017-10-03 11:54
+1

**Comment by thomaux** [comment] 2017-10-04 09:30
The issue seems to be caused by the fact the position of the forward slashes aren't ignored by the caret positioning. So what happens is:

1. You type 13, normally the caret should now be positioned after the first forward slash (this is not the case)
2. You type in 06, but the caret is now positioned between the 0 and 6
3. Typing in 1 next overwrites the 6, so you'll end up with 13/01
4. Inputting the rest of the year results in 2050. I'm not entirely sure what exactly's happening there, but it may well be related to the previous.

**Comment by RobinHerbots** [comment] 2017-10-04 19:32
This is a bug within the checkval fn. This will be fixed in version 4.x

**Comment by maddiedierker** [comment] 2017-10-04 19:43
Hi Robin, thanks for this library.  It's great!

I just ran into the same issue, and am wondering if this is a regression I can work around with an earlier version or something I'll have to wait for the 4.x to use. 

Thanks again.

**Comment by camj256** [comment] 2017-10-04 23:02
Anyone have a work-around? Just started digging into this as it's holding up a big release for us. Don't really want to drop the library but it might come to that.

**Comment by RobinHerbots** [comment] 2017-10-05 16:34
I will have a look tonight

**Comment by RobinHerbots** [comment] 2017-10-07 08:32
On the 4.x branch Backspace works for the datemask. This evening i investigate the wrong caret positioning on Android for the datemask.

**Comment by RobinHerbots** [comment] 2017-10-07 22:33
Normal input should work in the 4.x branch.  Todo is review backspaces

**Comment by RobinHerbots** [comment] 2017-10-08 09:46
Backspace ok.
Todo See #1713

**Comment by RobinHerbots** [comment] 2017-10-08 09:51
Damn, the fix for the Backspace causes a regression in the input. => is was due to requesting the desktop mode of the page!!

There should be a reliable way to detect if it is android even if the desktop page mode is selected, ...

Detecting wheter the touchstart event is supported can be used to detect a "non desktop device"  ;-)

**Comment by RobinHerbots** [comment] 2017-10-08 21:26
@unbreak, @kwadrax, @thomaux, @madelynkasula , @camj256,  

New jsfiddle (3.x) for testing

https://jsfiddle.net/cp3cunm0/11/

**Comment by camj256** [comment] 2017-10-08 23:26
Still broke the exact same way on my v20.  Android 7.0 and chrome.

**Comment by RobinHerbots** [comment] 2017-10-09 07:16
@camj256 , 

So you tested with https://jsfiddle.net/cp3cunm0/11/ ?

What exactly did you type?  Which keyboard where you using?  Can you do some debugging to see that the device is detected as a mobile one (by the inputmask)?

I tested on 3 tablets and 2 phones (android 6) and also on browserstack (android 7).
Can you reproduce the error on browserstack?

Can someone else also confirm?

**Comment by unbreak** [comment] 2017-10-09 08:11
@RobinHerbots, On my device (Nexus 5x, android 8, chrome, stack keyboard gboard) linked jsfiddle works fine!

**Comment by camj256** [comment] 2017-10-09 14:15
Oh so sorry guys. Its working fine. I'm used to mm/dd format and wasnt
paying attention last night. Its looking good!

**Comment by RobinHerbots** [comment] 2017-10-09 16:55
This issue can be xlosed?

**Closed as completed** 2017-10-09 18:33 UTC
Labels: Android, Dates, Main, Enhancement / Feature, Life example included => priority
