### ISSUE TITLE
Failing to enter 30/09 date

### ISSUE THREAD

**Issue by iliakan** [RobinHerbots/Inputmask#783] opened 2014-12-18 21:21 UTC
See the video http://screencast.com/t/PZx5JdVsM8Xb
I'm trying to enter 30.

**Comment by RobinHerbots** [comment] 2014-12-18 23:44
@iliakan , 

I will have a look at it.

**Comment by RobinHerbots** [comment] 2015-01-30 12:40
@iliakan , 

Sorry for the delay but the issue is fixed in version 3.1.59

**Closed as completed by RobinHerbots** 2015-01-30 12:40 UTC
Labels: Dates
