### ISSUE TITLE
Is it possible to create a definition for optional digits/characters?

### ISSUE THREAD

**Issue by koljada** [RobinHerbots/Inputmask#2524] opened 2021-07-07 09:21 UTC
- Describe the bug

I  want to add a definition for optional digits so I can use masks like this: `990.990.990.990`, instead of `999{0,1}` or `99[9]`.
The main reason for that is that I need to do a mask formatting on the server too and it seems like all other libraries use this approach for handling optional characters(e.g. https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.maskedtextbox.mask?view=net-5.0#remarks).

Is it possible at all? I tried to add a custom definition like this: `'0': { validator: "^[0-9]{0,1}$" }` but it's not optional.

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/koljada/xcmuvon6/56/

- OS: Windows 10
- Browser: Chrome
- Inputmask version:  3.3.11

**Comment by RobinHerbots** [comment] 2021-07-08 13:30
@koljada ,

I can add the optionallity to the definition, so that the M$ behavior is possible ;-)

**Comment by koljada** [comment] 2021-07-08 13:49
@RobinHerbots Thanks) It would be nice

**Comment by RobinHerbots** [comment] 2021-07-13 21:40
Hi @koljada , 

I added the optional option to the definitions.  Can you have a try with the latest version.  You can find it in the dist folder.

Can you try by adding the optional: true option to the definition.

**Comment by RobinHerbots** [comment] 2021-07-14 14:26
@koljada,

You should try with 5.0.7-beta.7

**Comment by koljada** [comment] 2021-07-18 14:05
@RobinHerbots Thanks, I'll try it soon

**Comment by nachotisnes** [comment] 2022-02-09 16:41
I'm facing the same issue, using 5.0.7

I tried to do this using this definition:
im = new Inputmask(["900.900.900.900"], 
		{greedy:false, 
                  numericInput: false, 
                  jitMasking:true,
                  definitions:{
                  '0': {
                    validator:"[0-9]",
                    optional:true
                    }
                  }});

Am I missing something? I created a fiddle to ilustrate my point; https://jsfiddle.net/itisnes/nther3La/1/

In that sample, i would expect both fields to act in the same way.

Thanks!

**Comment by RobinHerbots** [comment] 2022-02-24 14:38
@nachotisnes ,

Hmm there seems to be some regression.

**Comment by RobinHerbots** [comment] 2022-02-24 15:56
@nachotisnes ,

This is fixed in 5.0.8-beta.15

**Closed as completed by RobinHerbots** 2022-02-24 15:56 UTC
Labels: Enhancement / Feature, Regression

**Comment by nachotisnes** [comment] 2022-02-24 15:57
@RobinHerbots thanks! I'll try it soon :)
