### ISSUE TITLE
inputmask decimal with integerDigits or digits with maxlength can cause Browser freezed

### ISSUE THREAD

**Issue by DatXN** [RobinHerbots/Inputmask#889] opened 2015-04-23 09:12 UTC
We are found a bug in the inputmask plugin:
• When you are apply the input mask decimal with length check (ingegerDigit or digit with maxlength constrant) -> When user try to add more number or enter more character -> Browser is freezed
• You can try on: http://jsfiddle.net/8Jpdd/666/

Can you verify this bug?

**Comment by jmanos** [comment] 2015-04-23 22:19
Looking at the source code of the inputmask used in that jsfiddle, it seems like you (DatXN) are using an older version of inputmask. 

However, the problem is still present in the latest version. The infinite loop caused here is present at the same place as in #870, so fixing one of these issues will likely fix the other (Input 2 in DatXN's jsfiddle is the same condition mentioned in #870).

**Comment by DatXN** [comment] 2015-04-24 02:34
@jmanos You're right, but I also found that this bug occurs not only when you add '.', but also when you add another number when the input already is at its max length stage.

**Comment by RobinHerbots** [comment] 2015-04-28 14:22
The bug is fixed in the latest version on github. (not released)

**Closed as completed by RobinHerbots** 2015-04-28 14:22 UTC
Labels: Numerics, Main
