### ISSUE TITLE
Country Code Problem

### ISSUE THREAD

**Issue by tcagkansokmen** [RobinHerbots/Inputmask#2397] opened 2020-09-24 09:17 UTC
I need to mask "international country code" field.

It must be like (+... (999) 999 99-99)

It may have;
+90 444 444 44-44
or
+121 444 444 44-44
or
+1 444 444 44-44

It means; coutnry code may have 1, 2 or 3 digits.

How can this be possible?

**Comment by RobinHerbots** [comment] 2020-10-01 20:25
@tcagkansokmen , 

This mask
```Inputmask("+(1|\\90|221) (999) 999 99-99").mask("test1");```
should do but it doesn't.

There is a bug within the alternation logic.
I will try to fixed it but my time is very limited.

I should find a way that I can spend 1 day a week for developing on the inputmask.  Some fundraising so that I can justify my work.

**Comment by RobinHerbots** [comment] 2020-10-20 19:24
Hi @tcagkansokmen, 

The issue is fixed in version 5.0.6-beta.18 

Best regards, 
Robin

**Closed as completed by RobinHerbots** 2020-10-20 19:24 UTC
Labels: Multi & Alternation, Enhancement / Feature
