### ISSUE TITLE
Placeholders with multiple masks

### ISSUE THREAD

**Issue by garrettboatman** [RobinHerbots/Inputmask#997] opened 2015-08-07 18:17 UTC
There seems to be a bug with having multiple masks on the page with different placeholders.

This does not work as expected:

```
<input data-inputmask-mask="999-99-9999" type="text">
<input data-inputmask-mask="m/d/y" data-inputmask-placeholder="MM/DD/YYYY" type="text">

<script type="text/javascript">

$('input[data-inputmask-mask]').inputmask({
   placeholder: ' ',
   showMaskOnHover: false,
   showMaskOnFocus: true,
});

</script>
```

The placeholder works correctly with the second input, but when you begin to type in the first input, the second input's placeholder gets inserted and messes up. It's a weird context issue.

Writing a `$.each` fixes the issue, but this behavior should probably work without iterating through the inputs.

```
<script type="text/javascript">

$('input[data-inputmask-mask]').each(function() {
   $(this).inputmask({
      placeholder: ' ',
      showMaskOnHover: false,
      showMaskOnFocus: true,
   });
});

</script>

```

**Comment by RobinHerbots** [comment] 2015-09-02 09:55
@garrettboatman , 

I cannot reproduce the problem with the latest version.

Can you create a jsfiddle to point out the case.

**Comment by garrettboatman** [comment] 2015-09-02 16:50
You got it! http://codepen.io/garrettboatman/pen/rONXGx

**Comment by danilG** [comment] 2015-09-02 19:01
Thank you, Garrett!
I'd tested your examples, and I have found that I'm using not latest version.
After replacing to latest version 3 all gone work!

> Среда,  2 сентября 2015, 9:50 -07:00 от Garrett Boatman notifications@github.com:
> 
> You got it!  http://codepen.io/garrettboatman/pen/rONXGx
> —
> Reply to this email directly or  view it on GitHub .

---

С уважением, Данил Газизов,
ICQ: 203-010-703
skype: danil.gazizov
email: eurobax@mail.ru

**Comment by RobinHerbots** [comment] 2015-09-03 15:23
@garrettboatman , 

This is already fixed in the latest version.

http://codepen.io/anon/pen/BoyQRa

**Closed as completed by RobinHerbots** 2015-09-03 15:23 UTC
Labels: Main
