### ISSUE TITLE
Cannot erase input value through mask symbols (Android 4.4, Android 4.2)

### ISSUE THREAD

**Issue by Enfree** [RobinHerbots/Inputmask#1090] opened 2015-11-01 19:11 UTC
There is a problem was reproduced under several devices 
- Android Chrome, Android 4.2
- Default browser, Android 4.4(either reproduced under genymotion emulator model motorola moto x)

All cases was reproduced only with Android default keyboard(!!!!)

Test case:
$("#field").inputmask({"mask": "+7(999)-999-999-99"});
Input 123456.
Got +7(123)-456-___-__
Try to erase text with <- button(backspace)
ER: text was erased
AR: cannot erase through '-' symbol. But if u put caret between '5' and '6', u can erase 4 and 5 with backspace.

Root cause is android problem, like http://stackoverflow.com/questions/22503559/backspace-not-firing-the-keyup-event-in-android-mobile
no keydown/keyup event fires with backspace pressing, only input event. 
Is there any workaround for inputmask?

**Comment by RobinHerbots** [comment] 2015-11-02 08:55
@Enfree , 

Can you try with the latest which has a fix for this.

**Comment by Enfree** [comment] 2015-11-02 10:09
@RobinHerbots 
Well, current problem is not reproduced, but now mask symbols can be deleted with backspace, actually i can clear input field and input whetever i want.
TC: +7(999)-999-999-999 mask
input: 123456,
result: +7(123)-456-**_-**_
Start erasing with backspace, got
+7(123)-456-**_-**_
+7(123)-456___-___
+7(123)-45___-___
+7(123)-4___-___
....
**_-**_
Besides i can input every symbols:
aaaaa___-___
After onblur:
+7(123)-456-**_-**_

**Comment by RobinHerbots** [comment] 2015-11-02 10:18
@Enfree , 

Hmm I cannot reproduce this.  I tested on Android 4.2.2 and latest Chrome

**Comment by Enfree** [comment] 2015-11-02 10:24
@RobinHerbots 
i tested on android 4.4 default browser, ill try under 4.2 chrome

**Comment by RobinHerbots** [comment] 2015-11-02 10:26
@Enfree , 

I just committed a little fix which might help

**Comment by Enfree** [comment] 2015-11-02 10:34
@RobinHerbots 
so strange. Did you use AOSP keyboard? I can reproduce under 4.2 chrome either.
I'll try new fix.

**Comment by evilangelmd** [comment] 2015-11-12 11:49
ok. at first backspace it doesen't trigger, but if you need to have 2 or 3 backspaces, it will continue to do it.

**Comment by thebrambo** [comment] 2016-01-15 15:07
Im doing a Regex with the inputmask, it works but it still has bugs when your in the middle of a string (mine uses spaces) and hit backspace. It looks like it jumps back to its original position (where the bug happens) when your select a different position with the mouse onclick.

Would greatly appreciate the effort ty!

**Closed as completed** 2016-01-26 13:19 UTC
Labels: Android
