### ISSUE TITLE
Inputmask with a _space_ as a placeholder and leap year date

### ISSUE THREAD

**Issue by shevchuk** [RobinHerbots/Inputmask#2451] opened 2021-01-15 13:04 UTC
The bug is pretty interesting itself because it is reproduced with a certain
set of dates (leap year dates (29.02.2020, 29.02.1948)

The way to reproduce the issue is to instantiate a regular inputmask and specify
a placeholder as empty space (or wider spaces such as U+2000, etc)

Steps:

Actual
1. Just start typing the date: '29.02...
2. The month (2) doesn't appear in the input field

Expected
The 29.02.1948 should be typed the same way as any other dates.

```
<html>
<head>
  <script src="inputmask/dist/inputmask.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const input = document.querySelector('#maskedInput')

      const im = new Inputmask({
        alias: 'datetime',
        inputFormat: 'dd.mm.yyyy',
        placeholder: ' ',
        showMaskOnHover: false,
        showMaskOnFocus: false,
      });

      im.mask(input);
    });
  </script>
</head>
<body>
<input id="maskedInput" value="">
</body>
</html>

```
- OS (linux or any other)
- Browser (chrome)
- Inputmask version (latest)

**Comment by RobinHerbots** [comment] 2021-02-23 12:31
@adlerdias, 

Thx for the PR with the unittests.  That is the reason I solved it today ;-)

@shevchuk, 

The issue is fixed in  v5.0.6-beta.37

**Closed as completed by RobinHerbots** 2021-02-23 12:31 UTC
