### ISSUE TITLE
Android 6 issue - Samsung device keyboard 

### ISSUE THREAD

**Issue by ionutmaita** [RobinHerbots/Inputmask#1818] opened 2018-02-06 12:34 UTC
Hi,
I am using your library for a hybrid app.

When the caret reaches the group separator position, it remains behind with one digit.

I tried to use the version 4 beta which solves the defect , but the upgrade causes big rendering issues on iOS devices.

The problem can be reproduced on Samsung devices with Android 6 version only.
The problem is fixed on Android 7+.

What I want :
123 4567 890123

what I get :
123 678 904

This is my use
$('#inputmask-decimal').inputmask("+++999/9999/99999+++");

You can test it here for yourself http://plnkr.co/edit/3vVbJl7qA20v8XqOQEYJ?p=preview
To test directly on the android device, you can use this url: http://run.plnkr.co/UuU7o05kJz2zacD4/

Using version : 3.3.11

Thanks!

**Comment by RobinHerbots** [comment] 2018-02-07 07:02
@ionutmaita , 

What rendering issues do you have in version 4?

**Comment by RobinHerbots** [comment] 2018-02-12 13:27
@ionutmaita , 

Can you retry with beta 12

**Comment by ngfk** [comment] 2018-04-17 13:35
Hey @RobinHerbots,

I'm also running into this issue (v3.3.11). Beta 12 is not available so I tried with the latest beta (48), with this version I am unable to enter any characters. I also tried beta 14, the problem seems to be fixed in that version.

**Comment by RobinHerbots** [comment] 2018-04-17 13:52
@ngfk , 

I need more info.  Can you create a jsfiddle with the exact mask and options you are trying.
Also is predictive text enabled on the android device

**Comment by ngfk** [comment] 2018-04-17 14:03
I'll see if I can reproduce it with a jsfiddle

**Comment by ngfk** [comment] 2018-04-17 14:57
I am running an android emulator that shows this behaviour, emulator info:

GBoard keyboard, no predictive text.
![image](https://user-images.githubusercontent.com/25618095/38877240-8bf60408-425e-11e8-97c0-5301f15dde29.png)

On this device the beta 12 fiddle fixed the issue, on beta 48 the input box accepts the numbers but not the letters.

* [beta 12](http://jsfiddle.net/ngfkoster/ukep8mc5)
* [beta 12 result only](http://jsfiddle.net/ngfkoster/ukep8mc5/embedded/result/)
* [beta 48](https://jsfiddle.net/ngfkoster/hkrkaopb/)
* [beta 48 result only](http://jsfiddle.net/ngfkoster/hkrkaopb/embedded/result/)

**Comment by RobinHerbots** [comment] 2018-04-17 19:54
https://jsfiddle.net/hkrkaopb/2/

**Comment by RobinHerbots** [comment] 2018-04-18 06:10
@ngfk, 

It seems on Android 8, when you enter a number the caret position is like normal, but when you enter a character you get a selection of that character, which causes the inputfallback to misinterpret what happens.  Why is that?

**Comment by RobinHerbots** [comment] 2018-04-18 06:35
@ngfk , 

I pushed a fix on github.  Can you have a try with https://jsfiddle.net/hkrkaopb/2/

**Comment by ngfk** [comment] 2018-04-18 06:43
Awesome, I'll give it a try i about an hour

**Comment by ngfk** [comment] 2018-04-18 08:32
@RobinHerbots Works now, thanks!

Maybe a side question but do you have an assumption when to expect the stable release of version 4.0.0.

**Comment by RobinHerbots** [comment] 2018-04-18 08:51
@ngfk , 

You can already use the next version on npm.
I will release 4.0.0 in may.

**Closed as completed by RobinHerbots** 2018-04-18 08:51 UTC
Labels: Android, Main, IOS/OSX
