### ISSUE TITLE
inputmask overwrites the jquery.val function

### ISSUE THREAD

**Issue by destanoglu** [RobinHerbots/Inputmask#871] opened 2015-04-10 11:40 UTC
Hi,

First of all these are my mask options;
element.inputmask( {
                                alias: "numeric",
                                rightAlign: true,
                                autoUnmask: true,
                                digits: "0"
                            } );

After masking operation I set the value of the element by jquery val() function to zero ("0"). But your library catches the blur event and reset the element to "" (empty) in writeBuffer() method of your library.
Will you please suggest me a way to set the value of the masked element programatically.

Yours sincerely.

Onur

**Comment by destanoglu** [comment] 2015-04-10 11:56
"Google 41.0.2272.118 m" is the version of  my browser.

**Comment by destanoglu** [comment] 2015-04-10 12:08
Hacky solution :
1- remove the mask by inputmask("remove")
2- set the value using element.val()
3- set the mask by inputmask( {
alias: "numeric",
rightAlign: true,
autoUnmask: true,
digits: "0"
} );

But there should be a more convenient way of doing these kind of operations ????

**Comment by RobinHerbots** [comment] 2015-04-13 06:11
@feralanPaladin , 

This seems related to #786

**Comment by RobinHerbots** [comment] 2015-05-04 12:16
duplicate of #786

**Closed as completed by RobinHerbots** 2015-05-04 12:16 UTC
Labels: Numerics
