### ISSUE TITLE
Bug after typing dot

### ISSUE THREAD

**Issue by bshafiei-ir** [RobinHerbots/Inputmask#2146] opened 2019-06-23 08:17 UTC
When I type decimal numbers with dot, when I want edit again number format will missed.

![image](https://user-images.githubusercontent.com/19801131/59973424-0c549600-95b5-11e9-8fc6-498592883794.png)

@RobinHerbots

**Comment by RobinHerbots** [comment] 2019-06-24 21:33
@bahmansh , 

Working on it.

**Comment by RobinHerbots** [comment] 2019-06-26 23:30
@bahmansh, 

The issue is partially fixed.
Number corruption should be fixed.
Except when you enter 123456 and place a dot between 3 and 4 or somewhere else between.

Also working on that ;-)

**Comment by RobinHerbots** [comment] 2019-06-28 13:39
#2152

**Closed as completed** 2020-03-03 13:10 UTC
Labels: Numerics, Regression
