### ISSUE TITLE
numericInput - first char issue

### ISSUE THREAD

**Issue by mako** [RobinHerbots/Inputmask#56] opened 2012-06-08 07:20 UTC
Hi!

If I declared a numeric input like below, the first char is "not working".
If I hit the left arrow key (move to the 2 position from right) works fine and I can write something like : "€ ___.545.454,5_"

No error in firebug, just I can't write the first number.

``` html
<script type="text/javascript">
    $(function(){
        $('#test').inputmask('€ 999.999.999,99', { numericInput: true });
    });
</script>
<form>
    <input type="text" name="money" id="test" />
</form>
```

**Comment by RobinHerbots** [comment] 2012-06-08 08:01
Hi Miko,

The issue is fixed in the latest version.

Best regards,

Robin

2012/6/8 Mikó Zoltán <
reply@reply.github.com

**Comment by mako** [comment] 2012-06-08 08:26
omg! 24min.
you are the fastest! :)

**Comment by RobinHerbots** [comment] 2012-06-08 08:42
;-) thx!

2012/6/8 Mikó Zoltán <
reply@reply.github.com

**Comment by mako** [comment] 2012-06-08 11:56
Oh, something wrong in here :S
If I have some default data in the input field, or change the value in runtime, the result are not correct.
Sometimes the first char from right is not the correct place.

Try this:

``` javascript
$(function(){
    $('#test').val('123456');
    $('#test').inputmask('€ 999.999.999,99', { numericInput: true }); //=>  "___._12.345,6_"
});
```

but this seems ok:

``` javascript
$(function(){
    $('#test').val('1234567');
    $('#test').inputmask('€ 999.999.999,99', { numericInput: true }); //=> "___._12.345,67"
});
```

can you help me? thx!

**Comment by RobinHerbots** [comment] 2012-06-08 12:39
Can you create an example on jsfiddle, that's easier to see the exact problem.  

best regards, 

Robin

**Comment by RobinHerbots** [comment] 2012-06-08 14:51
problem is in the checkval for numericInput, ... will post a fix soon ;-)

**Comment by RobinHerbots** [comment] 2012-06-08 21:28
the lastest version should fix the issue

Robin

**Comment by mako** [comment] 2012-06-11 06:13
Ah, works perfectly!
Thx!

**Closed as completed** 2012-06-11 08:57 UTC

**Comment by mako** [comment] 2012-06-12 07:47
Hi!

Can you look at this?: http://jsfiddle.net/3tstg/
How can I prepopulate a float?

**Comment by RobinHerbots** [comment] 2012-06-12 09:47
fixed!

I really have to add some unittests, ... nobody in the mood to create some?

**Comment by mako** [comment] 2012-06-12 10:00
not perfect yet :S
http://jsfiddle.net/3tstg/2/

**Comment by RobinHerbots** [comment] 2012-06-12 11:31
check out http://jsfiddle.net/3tstg/3/

2012/6/12 Mikó Zoltán <
reply@reply.github.com

**Comment by mako** [comment] 2012-06-12 12:24
perfect! 
thx.

is it possible somehow to avoid having enter all zeros after the decimal point with a mask like this: '999 999.99'
I mean that by default the last 2 digits are always zero, but if I hit the comma the cursor step after the decimal point, and I can write the last 2 digits.

**Comment by RobinHerbots** [comment] 2012-06-12 13:15
You may open a new issue for that, ... so ... not yet ;-)

btw there is also a decimal alias in the numeric extentions

2012/6/12 Mikó Zoltán <
reply@reply.github.com

**Comment by mako** [comment] 2012-06-12 13:26
yes, I know, but I need it with money format :)

anyway, thx for the fixes!
