### ISSUE TITLE
'Decimal'. New entered value is automatically prefixed with '.'

### ISSUE THREAD

**Issue by mvysh** [RobinHerbots/Inputmask#2189] opened 2019-09-18 15:24 UTC
**Describe the bug**
For 'decimals' when number with fractional part was previously entered, then selected (CTRL + A) and user types some new number, it is automatically prefixed by a dot.

**Live example**
123.123 was entered. Highlight the number with CTRL + A and start to type in new number. E.g. 456. The result will be .456 (starting with '.').

**Please complete the following information:**
- Windows
- Chrome
- Inputmask version 5.0.0-beta.262

**Additional context**
I'm using following parameters for initialisation:

```
$(".cl").inputmask(
        "decimal",
        {
            placeholder: ' ',
            groupSeparator: ',',
            radixPoint: '.',
            autoUnmask: true,
            _radixDance: false,
        }
    );
```

**Comment by mortenfa** [comment] 2019-09-27 08:37
You can work around it until it's fixed with a onFocus handler setting the value to 0

$(selector).on('focus', function() {
            $(this).inputmask("setvalue", 0);
        });

**Comment by RobinHerbots** [comment] 2019-09-27 13:52
@Vishnja ,  @mortenfa ,

The issue is fixed in v5.0.0-beta.272

**Closed as completed by RobinHerbots** 2019-09-27 13:52 UTC
Labels: Numerics

**Comment by mortenfa** [comment] 2019-09-29 16:28
Still not working, same result with currency

```
$("#Selector").inputmask('currency', {
    digits: 2,
    allowMinus: false,
    groupSeparator: '.',
    rightAlign: false,
    radixPoint: ',',
    prefix: '',
    removeMaskOnSubmit: true
});

```

**Comment by RobinHerbots** [comment] 2019-09-30 09:45
@mortenfa , 

That is an other issue I am working on.
