### ISSUE TITLE
Possible to replace spetial characters from mask

### ISSUE THREAD

**Issue by devrus91** [RobinHerbots/Inputmask#362] opened 2013-10-25 10:32 UTC
For exmaple we have a mak on input (999)999-9999
If i select a ( and press any digit number ( will be replaced with this digit number
after input lose focus it was replaced back to (

**Comment by RobinHerbots** [comment] 2013-10-25 11:03
I will have a look at it.

2013/10/25 ruslanfedoseenko notifications@github.com

**Comment by RobinHerbots** [comment] 2013-10-25 11:07
@ruslanfedoseenko , 

Which version are you using from the inputmask and which browser(s).

Can you provide an example on jsfiddle as I cannot reproduce the behavior.

Best regards, 

Robin

**Comment by devrus91** [comment] 2013-10-25 11:08
latest version from github. Chrome  30.0.1599.101
it was reproducible on filled in input and also throws unhandled exception 
Uncaught TypeError: Cannot call method 'split' of undefined jquery.inputmask.js:1720
keypressEvent jquery.inputmask.js:1720
eventHandler.handler jquery.inputmask.js:1287
x.event.dispatch jquery-latest-min.js:5
y.handle

**Comment by devrus91** [comment] 2013-10-25 11:23
here is jsfidle example
http://jsfiddle.net/FhKxV/2/

**Comment by devrus91** [comment] 2013-10-25 11:32
May be i have misled you by saying select, actualy i mean highlight (put coursor on it and press Shift+Right Arrow)

**Comment by RobinHerbots** [comment] 2013-10-25 12:10
@ruslanfedoseenko , 

Fixed in the latest version

**Closed as completed by RobinHerbots** 2013-10-25 12:10 UTC
