### ISSUE TITLE
Malfunction with american date format

### ISSUE THREAD

**Issue by cloudy-reports** [RobinHerbots/Inputmask#1919] opened 2018-06-25 17:41 UTC
Hello, 
I  use Ubuntu 16.04, FireFox 60.0.2(64bit) and I have a next source code for using date inputmask

HTML
<input id="Settlement_Start_Date" name="Settlement_Start_Date" value="" placeholder="m/d/yyyy" size="" im-insert="false" style="width: 94px;" type="text">

JS
$(this).inputmask({
	alias: "datetime",
	inputFormat: "m/d/yyyy",
	clearIncomplete: true
});

After clicking on the input element, I can see that "placeholder" was changed to m/dyyyym. That's why I cannot enter a date in right american date format. I haven't any problems with with other formats. 

P.S. I have included a next js files:
inputmask.date.extensions.js
jquery.inputmask.js
jquery.inputmask.bundle.js

Version is the last(4.****).

**Comment by RobinHerbots** [comment] 2018-06-26 13:06
@cloudy-reports , 

This is a duplicate of #1830

**Closed as completed by RobinHerbots** 2018-06-26 13:06 UTC
Labels: Dates, Main, Enhancement / Feature

**Comment by cloudy-reports** [comment] 2018-06-29 07:38
Hello, 

my apologies, but I didn't understand, this bug already was fixed or this bug will be fixed in a future? Thanks for response.

**Comment by RobinHerbots** [comment] 2018-06-29 08:03
@cloudy-reports , 

It will be fixed in the a future release.  When you set placeHolder to "_", you should already be able to enter the date.

**Comment by cloudy-reports** [comment] 2018-07-12 10:44
Hello, I have tested with option placeholder: "_". It became a shade better. But I can't input a month with two numbers, such as 10,11 and 12.

**Comment by cloudy-reports** [comment] 2018-07-17 15:50
Hello, can You send a response on my request, please? Thanks.
