### ISSUE TITLE
Can't insert more than 2 letters in Firefox

### ISSUE THREAD

**Issue by aekrylov** [RobinHerbots/Inputmask#2114] opened 2019-05-17 12:25 UTC
**Describe the bug**
I've setup a custom definition that replaces numbers with letters (real use case is converting numbers to roman numerals). When used as a part of the mask with separators, it doesn't properly work in Firefox. Works fine in Chrome or when no other symbols present after the definition

**To Reproduce**
1. Open live example
2. Enter a digit in the input
3. In Firefox, the digit will be replaced with 'ab'

**Expected behavior**
The digit should be replaced with 'abc'

**Live example**
http://jsfiddle.net/x8vup6qc/

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 74, Firefox 66

**Comment by RobinHerbots** [comment] 2019-05-17 14:21
@aekrylov , 

I will need to try it on firefox, but have you tried with a newer version?

**Comment by aekrylov** [comment] 2019-05-17 14:33
@RobinHerbots  http://jsfiddle.net/5devcw90/1/ here's a fiddle with inputmask 4.x (`dist/min/jquery.inputmask.bundle.min.js`), i see the same behavior

**UPD**: also checked 5.x (http://jsfiddle.net/fdrktw0x/ ), all the same

**Comment by RobinHerbots** [comment] 2019-05-18 06:58
@aekrylov , 

I can confirm it doesn't work in firefox.  I will need to debug this step by step.

**Comment by RobinHerbots** [comment] 2019-05-19 06:27
Seems to be a sorting issue.

**Comment by RobinHerbots** [comment] 2019-05-20 06:33
Fixed in version 5.0.0-beta.158

**Closed as completed by RobinHerbots** 2019-05-20 06:33 UTC
Labels: Main, Life example included => priority
