### ISSUE TITLE
Pressing the K and M keys

### ISSUE THREAD

**Issue by hrolick-git** [RobinHerbots/Inputmask#1912] opened 2018-06-12 14:41 UTC
Hello. I have a question. I can not find a solution. 
Pressing the "K" in a field 00 is inserted two zero and pressing "M" = 00000 five zeros. How can I disable this feature?
_Thank you in advance for your response._

**Comment by RobinHerbots** [comment] 2018-06-12 16:13
@hrolick-git , 

Have a look at the numeric extensions.  Maybe I should make these shortcuts optional.

**Comment by hrolick-git** [comment] 2018-06-13 13:28
@RobinHerbots, thanks a lot for the quick response!
I hope this option will be available in the future.

Thank you for this wonderful plugin)

**Comment by shmidtelson** [comment] 2019-09-26 07:10
@RobinHerbots Hello, you added an feauture?

**Comment by RobinHerbots** [comment] 2019-09-26 11:23
@hrolick-git , @shmidtelson , 

Fixed in v5.0.0-beta.271

**Closed as completed** 2019-09-26 11:23 UTC
Labels: Numerics, Enhancement / Feature

**Comment by aszorenyi** [comment] 2019-09-26 19:38
@RobinHerbots I've just notice that this is a duplicate of an other issue created by me last year: #2024 .

Maybe you can close that one too. :)
