### ISSUE TITLE
Editing value after oncomplete fired cursor position

### ISSUE THREAD

**Issue by jameslouiz** [RobinHerbots/Inputmask#191] opened 2013-03-20 17:01 UTC
I have an input using '99/99/9999' as my mask.

When I fill in the field with for example: 19/03/9991 

and then delete a number and end up with 19/03/991_

and then try to add a number to the end it will not let me so trying to make it 19/03/9911 will not work..

Its like in order to put a character back in you need to go back to where you took one out otherwise it becomes locked until you delete it all or something.

**Comment by RobinHerbots** [comment] 2013-03-20 21:07
@jameslouiz ,

Can you provide a full example as I cannot reproduce the problem.

best regards, 

Robin

**Comment by jameslouiz** [comment] 2013-03-21 10:16
Hi,

Ive created a js fiddle:
http://jsfiddle.net/AEQ6Q/

And also, this screencast might help: 
http://www.screenr.com/DCb7

Thanks, James

**Comment by RobinHerbots** [comment] 2013-03-21 12:01
Hmm, ... what is the problem with that?  It is intentional that you can
only type characters when the caret is positioned at a correct position.
 There is no pushing of chars.

When using delete or backspace the caret is placed at the correct position.

best regards,

Robin

2013/3/21 jameslouiz notifications@github.com

**Comment by jameslouiz** [comment] 2013-03-21 12:28
Hi,

On further testing if you delete a character, for example the 3rd from the end, and the place the caret at the end and try to enter a character it does not work, event if you press the backspace.

cheers, James

**Comment by RobinHerbots** [comment] 2013-03-21 12:44
and if you set the caret position on the _ position?

2013/3/21 jameslouiz notifications@github.com

**Comment by jameslouiz** [comment] 2013-03-21 14:56
The same occurs. You click on the and and it move the cart to in front of the _ which is normal but doesn't let you type.

**Comment by RobinHerbots** [comment] 2013-03-21 15:04
Which browser are you testing in?  and which OS?

2013/3/21 jameslouiz notifications@github.com

**Comment by jameslouiz** [comment] 2013-03-21 15:22
Chroms, firefox, IE 7/8/9 -  windows 7. All my colleagues experience the same issue also

**Comment by RobinHerbots** [comment] 2013-03-21 15:35
huh?  I just tested you jsFiddle in chrome on windows 7  so typing 12345678
 then I delete say 8 and enter 9 then I delete 6 and enter 4, ... no
problem.  How is that possible

2013/3/21 jameslouiz notifications@github.com

**Comment by RobinHerbots** [comment] 2013-03-21 15:36
http://jsfiddle.net/AEQ6Q/1/

**Comment by jameslouiz** [comment] 2013-03-21 15:38
Okay try this:

type 11/11/1234

Blur

Delete 2

Blur 

Then try and type again.

**Comment by RobinHerbots** [comment] 2013-03-21 15:40
By delete 2 what do you mean, ... delete the 2 or delete 2 characters?

**Comment by jameslouiz** [comment] 2013-03-21 15:41
Delete the number 2

**Comment by RobinHerbots** [comment] 2013-03-21 15:42
hmm that works without problem, ... but I noticed when deleting say 2 an 3 with a selection then blur, refocus, the caret jumps to the end, ... this should be better at the first open position

**Comment by RobinHerbots** [comment] 2013-03-21 15:43
which version do you use of the mask, ... use the versions from the dist folder

**Comment by jameslouiz** [comment] 2013-03-21 16:05
Im using the very latest version. Yes the caret jumping to the end could be root of this issue but did you notice how you cannot type after refocusing?

**Comment by RobinHerbots** [comment] 2013-03-21 16:12
no, ...

**Comment by RobinHerbots** [comment] 2013-03-21 16:18
do you want to be able to overtype?

**Comment by jameslouiz** [comment] 2013-03-21 16:38
Ideally yes. I'm using this plugin on a very large Loan provider and this is used on the applications page. They get literally 1000's of applications a day and if something can 'break' it will and no doubt there will be people, albeit dump people, but people who cannot complete the application. I'm not sure of a work around so your input is greatly appreciated..

**Comment by RobinHerbots** [comment] 2013-03-21 20:51
@jameslouiz ,

try the insertMode: false as option in the mask

**Comment by RobinHerbots** [comment] 2013-04-25 12:55
@jameslouiz , 

I think this issue is the same as issue 196.  There was a problem when you enter a mask and after that you tyoe a new char but anywhere before the last char.  This is fixed now so can you retest your issue.

Feedback would be appreciated.!!

best regards, 

Robin

**Closed as completed** 2013-05-12 09:44 UTC
Labels: Main

**Comment by LostSenSS** [comment] 2014-05-28 09:51
@RobinHerbots Just one remark: "insertMode" option absent in the description at https://github.com/RobinHerbots/jquery.inputmask

**Comment by RobinHerbots** [comment] 2014-05-28 14:04
Yes i need to update the readme
