### ISSUE TITLE
Script looping start when add '.' between decimal values

### ISSUE THREAD

**Issue by ankurdhrusoft** [RobinHerbots/Inputmask#870] opened 2015-04-10 05:03 UTC
Script looping start when add '.' between decimal values
e.g.
if add 1000 and try to add '.' after 10, then its start looping
but its working fine while if we add like 10.00 continuously

i m using this script
$('.floatval').inputmask("decimal",{digits:2});

**Comment by RobinHerbots** [comment] 2015-04-10 06:36
@ankurdhrusoft , 

I will have a look. Thx for reporting.

**Comment by jmanos** [comment] 2015-04-22 21:46
Yeah, I noticed this as well.

It occurs at the following code in the `setValidPosition` function of inputmask when `vps[i].input` is ".":

``` javascript
if (void 0 != t) for (var posMatch = j; posMatch < getMaskLength() && (null == t.match.fn && vps[i] && (vps[i].match.optionalQuantifier === !0 || vps[i].match.optionality === !0) || null != t.match.fn); ) { 
    if (null == t.match.fn || !opts.keepStatic && vps[i] && (void 0 != vps[i + 1] && getTests(i + 1, vps[i].locator.slice(), i).length > 1 || void 0 != vps[i].alternation) ? posMatch++ : posMatch = seekNext(j), positionCanMatchDefinition(posMatch, t.match.def)) { 
        valid = isValid(posMatch, t.input, !0, !0) !== !1, j = posMatch;
        break;
    }
    valid = null == t.match.fn;
 }
```

**Comment by ankurdhrusoft** [comment] 2015-04-23 05:44
Thank u very much for very nice support...
Your input validation plugin is awesome.... [?]

But do not understand, how can i fixed this [?]

On Thu, Apr 23, 2015 at 3:17 AM, jmanos notifications@github.com wrote:

> Yeah, I noticed this as well.
> 
> It occurs at the following code in the setValidPosition function of
> inputmask when vps[i].input is ".":
> 
> if (void 0 != t) for (var posMatch = j; posMatch < getMaskLength() && (null == t.match.fn && vps[i] && (vps[i].match.optionalQuantifier === !0 || vps[i].match.optionality === !0) || null != t.match.fn); ) {
>     if (null == t.match.fn || !opts.keepStatic && vps[i] && (void 0 != vps[i + 1] && getTests(i + 1, vps[i].locator.slice(), i).length > 1 || void 0 != vps[i].alternation) ? posMatch++ : posMatch = seekNext(j), positionCanMatchDefinition(posMatch, t.mat
>  ch.def))
>   {
>         valid = isValid(posMatch, t.input, !0, !0) !== !1, j = posMatch;
>         break;
>     }
>     valid = null == t.match.fn;
>  }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RobinHerbots/jquery.inputmask/issues/870#issuecomment-95347510
> .

## 

Love & Prayer
Ankur

**Comment by RobinHerbots** [comment] 2015-04-23 07:49
I will have a look at it next week.
My dauhter Tess is born past thursday, so I have other priorities for the moment :-)

**Comment by jpontet** [comment] 2015-04-24 09:00
Robin- I just want to point you in the right direction with this issue as it is something that we have had a problem in our company with as well and we have done our best to do a quick fix before you are able to fix it yourself- I expect you know the code pretty much inside out afterall!

So, I found that there is an endless loop (line 238) which appears to be caused because the code "positionCanMatchDefinition(posMatch, t.match.def)" (line 242) does not return TRUE and so the for loop does not break.

To reproduce the issue:
- Set decimal masking on a field
- Enter 2 digits, e.g. 56
- Then enter a decimal between the 2 digits e.g 5.6
- It should then enter a continuous loop and the page freezes

I hope this help.

**Comment by RobinHerbots** [comment] 2015-04-24 13:31
Thx for the info.  A fix will follow soon.

**Comment by RobinHerbots** [comment] 2015-05-04 09:54
@ankurdhrusoft, @jpontet ,

Fixed in the latest commit

**Closed as completed by RobinHerbots** 2015-05-04 09:54 UTC
Labels: Numerics, Main

**Comment by jpontet** [comment] 2015-05-05 08:14
@RobinHerbots thanks!
