### ISSUE TITLE
Currency mask works incorrectly on Android Chrome v58

### ISSUE THREAD

**Issue by IRuslan** [RobinHerbots/Inputmask#1617] opened 2017-06-12 11:56 UTC
Even on the demo site, there is a set of anomalies with Currency mask type.
Cursor randomly positioned, 0 digit does not work at the end of the string.

See video for details - https://youtu.be/H5JfzDOtZpQ

**Comment by nicolasmarlu** [comment] 2017-06-22 17:43
Actually, I´ve the same problem.

**Comment by movedoa** [comment] 2017-06-26 11:30
Same problem here

**Comment by filipeve** [comment] 2017-07-05 23:04
Same problem here. https://jsfiddle.net/filipeve/ooa3utw1/
Platform: Android 4.4+ / Chrome or Firefox (Latest versions)
Case 1: Try input 50,00. Does not accept 0 of 50.
Case 2: Try input 56,03. Is changed to 56,30.

**Comment by seggington** [comment] 2017-08-24 20:55
I have a JQM web app that I just updated to inputmask 3.3.8, in order to resolve the same issue as mentioned in #1648, when run on an Android based device.  The issue is still not resolved.  

The cursor position jumps around in currency and percentage fields.  If I specify numericInput: true, it will not allow entry of the last decimal place, jumping back to the second from last position.  I have tried the following formats, both with and without numericInput: true:

$("#callbackFormResponse").inputmask({ alias: 'currency', autoUnmask: true });
$("#callbackFormResponse").inputmask({ alias: 'numeric', groupSeparator: ',', autoGroup: true, digits: 2, digitsOptional: false, prefix: '$ ', placeholder: '0', autoUnmask: true });
And even:
$("#callbackFormResponse").inputmask({ mask: "$ 999.99", autoUnmask: true });

Is there anything that needs to be defined in order to work correctly on an Android device?

Android version: 6.0.1
Chrome version: 59.0.3071.125
JQuery: 2.1.1
JQuery Mobile: 1.4.5

You're help is greatly appreciated.

**Comment by RobinHerbots** [comment] 2017-08-25 07:04
Specify the androidHack option. When I find some time In Will look into the issue again

**Comment by seggington** [comment] 2017-08-25 14:35
Thank you for the reply, Robin.

You’re referring to the ‘androidHack: "rtfm"’ in the android readme?

Does this also apply to 3.3.7, or only 3.3.8 and later?

**Comment by seggington** [comment] 2017-08-25 14:45
When I enable the androidHack, neither the entered digits, nor the mask, appear in the input field.  I do see the submit button becoming enabled, based upon the 'IsComplete' trigger, but no text is transferring from the hidden field to the input field.  It appears that the hidden field is not hidden.  I can barely see the color masked password field overlaying rendered div.

**Comment by seggington** [comment] 2017-08-25 16:09
The androidHack still does not allow the entry of a 0.

We are to begin UAT shortly, so if you get an opportunity to look into it, I would greatly appreciate it.

**Comment by RobinHerbots** [comment] 2017-08-25 20:48
updated fiddle for testing https://jsfiddle.net/ooa3utw1/10/

**Comment by seggington** [comment] 2017-08-25 21:14
Thank you, Robin.

That is closer, but still won’t accept a 0 in the last decimal place.

**Comment by RobinHerbots** [comment] 2017-08-25 21:16
Steps to reproduce:  
first see comment https://github.com/RobinHerbots/Inputmask/issues/1617#issuecomment-313250338
type 50,03
press backspace until 5|,00
type: 0.0  => caret jumps back



I can also simulate in a desktop browser.

**Comment by seggington** [comment] 2017-08-25 21:25
Sorry Robin, what am I attempting to reproduce?  How does this help resolve the issue with the last decimal place not accepting a 0?

**Comment by seggington** [comment] 2017-08-25 22:09
Thank you Robin,

You used the type 'tel'.  Very interesting

Which version did you use for that jsfiddle you sent?  They appear to be custom.

**Comment by seggington** [comment] 2017-08-26 19:38
Robin,

If I copy the inputmask.js, inputmask.numeric.extensions.js, and jquery.inputmask.js versions from the updated jsfiddle, and use the new mask details, it appears to work well...  at least, until you start backspacing to replace values.  Unfortunately, if the field already has a value, it immediately breaks upon any changes.

**Comment by seggington** [comment] 2017-08-26 19:56
When attempting to enter a value of 10.03, as an example; If you enter 0, after entering the period, the cursor jumps back in front of the decimal point.  If you enter period twice, the cursor jumps to the 2nd decimal place, allowing for entry of a value in the 2nd decimal place.

**Comment by RobinHerbots** [comment] 2017-09-05 13:08
@seggington , 

Can you have a test with https://jsfiddle.net/ooa3utw1/11/

**Comment by argumentus** [comment] 2017-09-06 07:41
@RobinHerbots ,
I have tested this fix on my example https://jsfiddle.net/argumentus/4t657qb5/ on android, but it still not work.

**Comment by RobinHerbots** [comment] 2017-09-06 08:37
@argumentus , 

This fix fixes the above mentioned mask.  Can you create a new issue for yours.
Can you also be more specific.  When exactly does it fail.  Describe the steps to reproduce.

Also which version of android?

**Comment by seggington** [comment] 2017-09-06 19:36
Sorry for the delay, Robin.  That appears to be working well.  Thanks for the fix.

Will this fix affect Phone masks or others, or is strictly numeric related?

**Comment by seggington** [comment] 2017-09-06 19:55
Robin, this latest fix does not appear to work with the addition of the numericInput: true setting.  The cursor stays at the right, and doesn't recognize (or at least doesn't show) and digits entered.

**Comment by RobinHerbots** [comment] 2017-09-06 21:08
@seggington , 
The changes also affect other masks.  numericinput is not tested currently.  I have concentrated on the numeric aliases without the numericinput option.  On android, the inputmask is based solely on the inputevent.  Detecting the user intention isn't always straightforward.  In most cases you can simulate android behavior on the desktop by setting the inputEventOnly option to true.

**Comment by movedoa** [comment] 2018-02-01 12:58
any news on this?

**Comment by RobinHerbots** [comment] 2019-11-04 11:28
Can anyone do some testing on android with version 5.0.0-beta

**Closed as completed** 2019-11-13 10:27 UTC
Labels: Android, Main, Enhancement / Feature
