### ISSUE TITLE
removeMaskOnSubmit

### ISSUE THREAD

**Issue by universe416** [RobinHerbots/Inputmask#1394] opened 2016-09-21 22:38 UTC
I don't think this is an actual issue with the plugin but rather me not understanding how to successfully set the removeMaskOnSubmit option.  Someone else installed the plugin and I'm trying to figure out how to correct it so that when a search is submitted, the mask is removed.  If I remove the attributes all together and just have the raw input sent to MySQL db, the query works fine, but I can't seem to get it to work with the input mask attributes.  In the JS file we have:
masked_inputs: function () {
        Inputmask().mask(document.querySelectorAll("input"));

and in our php file we have the following attributes:

data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 'digitsOptional': false, 'prefix': '$ ', 'placeholder': '0'"/>

When I add 'removeMaskOnSubmit': true as an additional attribute in the php file; it still doesn't work.  On the front-end, the attributes work, meaning the masks are displaying how they should; however, the parameter does not work when a search is submitted to our MySQL db. Thank you in advance for any assistance that can be provided in order to get this to work.

**Comment by RobinHerbots** [comment] 2016-09-22 07:28
@universe416 , 

Or you add the removeMaskOnSubmit to the data-inputmask attribute or add data-inputmask-removemaskonsubmit="true".  This options is triggered by a form submit,  Verify the formdata in the briowser dev tools.

**Comment by universe416** [comment] 2016-09-22 12:47
Thank for the reply Robin.  I'm not sure if part of your answer accidentally got deleted, but I don't understand what you wrote.  Like I said in my question, I added removeMaskOnSubmit  to the form attribute, and it does not work.  Perhaps you can provide a working example?

**Comment by RobinHerbots** [comment] 2016-09-22 13:35
@universe416 , 

Can you create a jsfiddle so I can see what you exactly did.

**Comment by universe416** [comment] 2016-09-22 13:40
I can't, unfortunately. 

 I tried to add the snippets of code here but it didn't work.  Is t possible to do a private screen share?

**Comment by RobinHerbots** [comment] 2016-09-22 13:53
@universe416 , 

https://jsfiddle.net/qddLqqgx/3/

Open the fiddle, open dev tools browser (f12) see in the network tab
Type something in the input press submit => verify formdata of the request.

Btw you can set code snippets by typing ```   at the beginning and ending

**Comment by universe416** [comment] 2016-09-22 14:02
The way your example is setup is exactly how I have added the attribute to the form; however, when I submit the search, its as though the form input parameter that I added the attribute to is skipped.  Its not just due to the removeMaskOnSubmit option; it no longer works when I add any data-inputmask options.  Could it be a conflict with something else?  The form works fine when I remove the data-inputmask attributes all together.

**Comment by RobinHerbots** [comment] 2016-09-22 14:08
@universe416 , 

When you submit your form what is the formdata.  Can put a copy here.  Or send it to my gmail if you prefer.

**Comment by universe416** [comment] 2016-09-22 14:29
What would be ideal is if we could do a screen share so I can show you the entire thing.  I'm happy to pay you for 30mins-hour of consulting if you would be willing.  I'm not a front-end dev expert (I deal mostly with DB mgmt).  Our front-end dev is currently away on vacation.

**Comment by RobinHerbots** [comment] 2016-09-22 14:40
@universe416 , 

Ok, but can this wait till monday?

**Comment by universe416** [comment] 2016-09-22 14:48
The sooner the better.  I'm going to keep torubelshooting it on my own.  Our front-end dev is coming back sometime next week (not sure what day).  Please let me know whenever you have the time to allocate and I'll let you know if I solved the problem by then.  Not sure how to get your email but I prefer not to post mine on this open post.

**Comment by sbosio** [comment] 2016-09-22 15:51
I've been struggling for almost one day with a similar problem. The value submitted still had the mask applied even when I have set the removeMaskOnSubmit option.

I'm using Ruby on Rails and imported this plugin JS files using the gem 'jquery-inputmask-rails' that packages your plugin for Rails, but I just realized that it's completely outdated.

It was solved using a Git fork of that gem that is keep up to date (now packages version 3.3.4)

**Comment by universe416** [comment] 2016-09-22 15:58
The jquery.inputmask.bundle.js file we have is our app indicates the follow:
/*!
- jquery.inputmask.bundle.js
- https://github.com/RobinHerbots/jquery.inputmask
- Copyright (c) 2010 - 2016 Robin Herbots
- Licensed under the MIT license (http://www.opensource.org/licenses/mit-license.php)
- Version: 3.3.1
  */

Robin, is this the not the most up-to-date version? If not, could this be the cause of our problem?

**Comment by universe416** [comment] 2016-09-22 16:11
I downloaded the most up-to-date file from Github and replaced it; same problem exists..

**Comment by RobinHerbots** [comment] 2016-09-22 17:14
Which scrips are loaded?

Op do 22 sep. 2016 18:11 schreef universe416 notifications@github.com:

**Comment by universe416** [comment] 2016-09-22 17:18
bower_components/jquery.inputmask/dist/jquery.inputmask.bundle.js

**Comment by RobinHerbots** [comment] 2016-09-23 07:35
@universe416 , 

Just a thought, is there somewhere in the code a binding to the submit event?

**Comment by universe416** [comment] 2016-09-23 13:14
Not sure...the form data is passed to a MySQL query.

**Comment by universe416** [comment] 2016-09-23 16:13
Hi Robin.  Can we communicate through email?

**Comment by RobinHerbots** [comment] 2016-09-23 17:04
Op vr 23 sep. 2016 18:13 schreef universe416 notifications@github.com:

**Comment by universe416** [comment] 2016-09-25 03:01
Hi Robin...do you realize that the jfiddle you created does not work?

**Comment by RobinHerbots** [comment] 2016-09-25 06:36
@universe416 , 

In a developers point of view it works.  Look at the submitted formdata.

**Comment by t0n1zz** [comment] 2016-11-14 04:33
sir i also have the same problem as this....i tried the same as what you write up there in jsfidle but not working... and also just downloaded the newest version...

**Comment by RobinHerbots** [comment] 2016-11-14 11:21
@t0n1zz , 

How are you submitting the data?

**Comment by GreenWisdom** [comment] 2016-11-14 15:04
Listen to Robin.

**Comment by t0n1zz** [comment] 2016-11-15 04:00
i am not sure how to answer that question, but i use laravel framework for handling backend... maybe that's will help?

**Comment by GreenWisdom** [comment] 2016-11-15 04:14
Are you using a jquery date picker of some sort?  I'm using the datepicker from uikit.

**Comment by t0n1zz** [comment] 2016-11-15 04:21
no, for date input i only using inputmask but beside using inputmask i also using this [https://github.com/1000hz/bootstrap-validator](url) for validating form input.

**Comment by GreenWisdom** [comment] 2016-11-15 04:43
what's the purpose of the date inputs in your application?  Are they date ranges? 
(e.g. min/begin date max/end date)

**Comment by GreenWisdom** [comment] 2016-11-15 04:54
nevermind. then. I'll grab some code relative to the thousands separator.

**Comment by t0n1zz** [comment] 2016-11-15 04:54
no, just make sure they type dd/mm/yyyy, 

but my problem is not in date input, i already have a way to handle that, my problem is in thousand separator... so when i type 1000000 it will appear 1.000.000, it just for better user experience and the problem is when i post the form.. 

what i expect is 15000000 and what i get is 15.000.000 and the result is what saved into my mysql database is 15 , just the number before thousand separator.... because my field in mysql is float not varchar

**Comment by GreenWisdom** [comment] 2016-11-15 04:59
No PHP included....This works for me...
`<input id="your_input" name="your_input" type="text" class="md-input" maxlength="14" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 'digitsOptional': false, 'autoUnmask': true, 'removeMaskOnSubmit': true"/>`

**Comment by GreenWisdom** [comment] 2016-11-15 05:00
BTW..if the field does not have a decimal, maybe consider changing the field type in MySQL to `BIGINT`

**Comment by GreenWisdom** [comment] 2016-11-15 05:04
I'm a little confused.  What does the input represent?  A date? number? decimal? geometry? sign language?

**Comment by t0n1zz** [comment] 2016-11-15 05:52
represent value for financial report and it will be too short if i using bigint so i use float since it have the biggest one.....

**Comment by t0n1zz** [comment] 2016-11-15 06:09
well i think we are talking a little out of scope... my question is just how to make removeMaskOnSubmit working.... since it is not working in here

**Comment by RobinHerbots** [comment] 2016-11-15 09:22
@t0n1zz , 

The removeMaskOnSubmit only works on a simple form submit.  When using an ajax call, the removeMaskOnSubmit is not used.  In the case you subscribe, I guess using autoUnmask and unmaskAsNumber will do.

If this doesn't work, create a new issue with an example in a jsfiddle.

I am going to close this issue.

**Closed as completed by RobinHerbots** 2016-11-15 09:22 UTC
Labels: Question
