### ISSUE TITLE
Different behaviour configuration by attribute vs initialization

### ISSUE THREAD

**Issue by mikeleber** [RobinHerbots/Inputmask#2530] opened 2021-07-16 06:11 UTC
I want to set the output format via data-attribute-outputFormat but i can´t get it work. It´s working for direct initialization but not with the attribute. Here my fiddle showing the problem: https://jsfiddle.net/mike_leber/upms95kg/10/

Would be nice if you can get me a little hint :-)

**Comment by mikeleber** [comment] 2021-11-14 00:25
Any news/planings in thus issued?

**Comment by RobinHerbots** [comment] 2021-11-17 09:34
@mikeleber,

The issue is fixed in version 5.0.7-beta.32

**Closed as completed by RobinHerbots** 2021-11-17 09:34 UTC
Labels: Dates, Main, Enhancement / Feature, Life example included => priority

**Comment by mikeleber** [comment] 2021-11-19 08:20
Great news, many thanks :-)
