### ISSUE TITLE
Bootstrap datepicker conflict

### ISSUE THREAD

**Issue by arnaldodg** [RobinHerbots/Inputmask#179] opened 2013-02-28 01:11 UTC
Hi... nice component =]

I found an issue with the bootstrap-datepicker:

<div class="input-append date datepicker" id="" data-date-format="dd/mm/yyyy" data-date-language="br">
  <input class="span10" type="text" value="" id="data" >
  <span class="add-on"><i class="icon-th"></i></span>
</div>

When used together the inputmask causes the page to freeze on getting focus =/
I even tried with showMaskOnHover: false... no success also.

Everything else works great!

Cheers,

Arnaldo

**Comment by RobinHerbots** [comment] 2013-02-28 08:26
Hi Arnaldo,

Can you make a jsFiddle which shows the problem.

Then I will have a look at it,

Best regards,

Robin

2013/2/28 arnaldodg notifications@github.com

**Comment by arnaldodg** [comment] 2013-02-28 13:54
Hi Robin =]

I am a newbie in this jsFiddle/GitHub world.
Can you point me a jsF of your own that includes the inputmask component so I can fork it?

Cheers, 

AD

**Comment by RobinHerbots** [comment] 2013-03-01 08:40
No problem ;-)

http://jsfiddle.net/V3KFh/

Robin

**Comment by arnaldodg** [comment] 2013-03-01 14:50
Hi Robin.

Finally I managed to gets thing in a JsF =]

http://jsfiddle.net/arnaldodg/Ajhbg/34/

I hope this is useful for this investigation o.O

Cheers

Arnaldo

**Comment by RobinHerbots** [comment] 2013-03-01 14:58
@arnaldodg 

In which browser do you have the problem?

**Comment by arnaldodg** [comment] 2013-03-01 15:04
I have only tested with Chrome v 21.0.1180.89
Can test with FF, but the mainstream env will be Chrome for sure (enterprise directives).

**Comment by RobinHerbots** [comment] 2013-03-04 15:14
I don't see the problem.  I tested the jsfiddle in Chrome 25.0.1364.97

**Comment by RobinHerbots** [comment] 2013-03-07 22:40
Indeed the whole browsers freezes when you apply the date alias.

I will try to find the cause

Robin

**Comment by arnaldodg** [comment] 2013-03-07 22:46
Hi Robin,

Sorry for being away for so long. My job is trying to kill me =]

Anyhow I must thank yo for your kind attention.
I hope I can help you with tests here.

Let me know...

Cheers, 

Arnaldo

**Comment by RobinHerbots** [comment] 2013-03-07 22:49
Hi @arnaldodg,

The datepicker can't deal with the placeholder dd/mm/yyyy.  This should be fixed in the datepickers code.

If you apply this mask with the basic placeholder it works

$('#simpleInput').inputmask('date',  { placeholder: "_"}); // Simple input as DatePicker
$('#compInput').inputmask('date', { placeholder: "_"}); // As component

http://jsfiddle.net/Ajhbg/36/

best regards, 

Robin

**Closed as completed by RobinHerbots** 2013-03-07 22:49 UTC
