### ISSUE TITLE
Problem with jquery.validate.unobtrusive.js and autoUnmask in Firefox and Chrome

### ISSUE THREAD

**Issue by repa7** [RobinHerbots/Inputmask#271] opened 2013-06-21 13:00 UTC
Hi Robin,

First of all your work is great, thx!

I have 2 problems if I include jquery.validate.unobtrusive.js and use autoUnmask:
1. The textbox is masked with 'decimal' and autoUnmask is true:
   In the textbox if I write 5.8 and press TAB the value is removed from the inputbox.
   If autoUnmask is false it works great.
2. The textbox is masked with '99-99-99' and autoUnmask is true:
   First I clicked on the Other textbox and I clicked on the Decimal textbox.
   If I click again on the Other textbox the cursor is on the second position and not on the first position.
   If autoUnmask is false it works great.

Here is my test.htm file:

&lt;!DOCTYPE html&gt;
&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
    &lt;head&gt;
        &lt;script src=&quot;Scripts/jquery-1.9.1.js&quot;&gt;&lt;/script&gt;
        &lt;script src=&quot;Scripts/jquery.validate.js&quot;&gt;&lt;/script&gt;
        &lt;script src=&quot;Scripts/jquery.validate.unobtrusive.js&quot;&gt;&lt;/script&gt;
        &lt;script src=&quot;Scripts/jquery.inputmask-2.2.33.js&quot;&gt;&lt;/script&gt;
        &lt;script src=&quot;Scripts/jquery.inputmask.date.extensions-2.2.33.js&quot;&gt;&lt;/script&gt;
        &lt;script src=&quot;Scripts/jquery.inputmask.extensions-2.2.33.js&quot;&gt;&lt;/script&gt;
        &lt;script src=&quot;Scripts/jquery.inputmask.numeric.extensions-2.2.33.js&quot;&gt;&lt;/script&gt;
        &lt;script type=&quot;text/javascript&quot;&gt;
            $(document).ready(function () {
                $(&quot;#decimal&quot;).inputmask(&quot;decimal&quot;, { autoUnmask: true });
                $(&quot;#other&quot;).inputmask(&quot;99-99-99&quot;, { autoUnmask: true });
            });
        &lt;/script&gt;
        &lt;title&gt;Test&lt;/title&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;form&gt;
        &lt;table&gt;  
            &lt;tr&gt;
                &lt;td&gt;
                    Decimal
                &lt;/td&gt;
                &lt;td&gt;
                    &lt;input type=&quot;text&quot; id=&quot;decimal&quot; /&gt;
                &lt;/td&gt;  
            &lt;/tr&gt;
            &lt;tr&gt;
                &lt;td&gt;
                    Other
                &lt;/td&gt;
                &lt;td&gt;
                    &lt;input type=&quot;text&quot; id=&quot;other&quot; /&gt;
                &lt;/td&gt;  
            &lt;/tr&gt;
        &lt;/table&gt;
        &lt;/form&gt;
    &lt;/body&gt;
&lt;/html&gt;

Regards,

Cs.

**Comment by RobinHerbots** [comment] 2013-06-21 13:06
@repa7 , 

Can you first retry with the latest version.  There are some fixes for the decimals.

Best regards, 

Robin

**Comment by repa7** [comment] 2013-06-24 07:40
Hi Robin,

I tested with version 2.2.49 and the result is the same.

Regards,

Cs.

**Comment by RobinHerbots** [comment] 2013-06-24 08:00
@repa7 , 

Ok, I will have a look at it.

Robin

**Comment by RobinHerbots** [comment] 2013-06-25 15:16
@repa7 , 

Can you create an example in jsfiddle as I cannot reproduce the behavior.

best regards, 

Robin

**Comment by repa7** [comment] 2013-06-28 08:27
Hi Robin,

I did it: 
http://jsfiddle.net/QTzgH/1/

Regards,

Cs.

**Comment by RobinHerbots** [comment] 2013-06-28 09:52
Updated http://jsfiddle.net/QTzgH/2/

Indeed

**Comment by RobinHerbots** [comment] 2013-06-29 22:32
@repa7 , 

I'm working on it.

best regards, 

Robin

**Comment by RobinHerbots** [comment] 2013-07-01 11:07
@repa7 , 

fixed in the latest version

**Closed as completed by RobinHerbots** 2013-07-01 11:07 UTC
Labels: Main

**Comment by repa7** [comment] 2013-07-05 09:12
Hi Robin,

It works great!

Thanks,

Cs.
