### ISSUE TITLE
Can't checkout latest commit or 2.6 branch with bower

### ISSUE THREAD

**Issue by nmackey** [RobinHerbots/Inputmask#408] opened 2014-01-14 04:36 UTC
I get error when trying to checkout jquery.inputmask using a commit hash. (I'm trying to get the IE8 fix.)

I would get the following error:
EMALFORMED Failed to read /var/folders/vm/wv5c853j7hldqgkctj9hfq900000gn/T/nicholasmackey/bower/jquery.inputmask-28756-pvNMaU/bower.json

At first I thought it was b/c your bower.json file isn't to spec (http://bower.io/#defining-a-package), but even if I update the bower.json file in my fork I continue to get a git checkout error:

ECMDERR Failed to execute "git checkout 7094571911c0620b459cfd428c855bd13aee17f9", exit code of #128

Anyone else having this issue?

**Comment by RobinHerbots** [comment] 2014-01-15 08:08
@nmackey , 

Be aware that the 2.6 branch is experimental and not stable. You should use the 2.x branch.

Maybe, the problem is that the bower.json points to the dist/jquery.inputmask.bundle.js which is not available in branch 2.6.   Or that the version in the bower.json is the same as the 2.x branch?

I will need to spend some time to see how bower work.

**Comment by nmackey** [comment] 2014-01-20 17:08
Yeah, I just wanted to use the latest in the 2.x branch.  I have worked around the problem by creating a new tag in my fork.  I don't know why it has issues with your branch, maybe it is your naming convention or something.  Bower updated last year and deprecated the component.json files convention and now uses the bower.json convention the details of which can be seen in the link in my initial post.

So just to clarify I can check out your tags with bower just fine, just not your branches.

**Comment by RobinHerbots** [comment] 2014-01-23 09:31
@nmackey , 

The issue for the bower package should be fixed now.

Can you verify?

Robin

**Closed as completed** 2014-01-23 10:15 UTC

**Comment by nmackey** [comment] 2014-01-23 15:00
Everything seems to work, I can now use bower install to checkout branches, tags, and commits from your repo.  Thanks for fixing.
