### ISSUE TITLE
Can't insert characters with combinations of keys [End] / [Home]

### ISSUE THREAD

**Issue by lmiguelmh** [RobinHerbots/Inputmask#196] opened 2013-03-23 20:50 UTC
Well, in an input text with any mask:
1.  Press any key ('a').
2.  Press [Home].
3.  Press any key ('a').
4.  Press [End].
5.  Repeat from step 1 again.

This behaviour varies with _placeholder=""_, or _insertmode=false_, being more evident with _placeholder=""_ and insertmode off (without).

**Comment by RobinHerbots** [comment] 2013-03-24 21:46
@lmiguelmh,

Thx for the feedback! 

I will fix these issues soon.

Best regards, 

Robin

**Comment by RobinHerbots** [comment] 2013-04-19 08:31
@lmiguelmh ,

Can you explain a bit more the problem?  It is not clear to me what the problem is.

Robin

**Comment by lmiguelmh** [comment] 2013-04-19 14:29
You can't insert characters at the end (even if you had enough space left). Write a character and then press HOME, then END, and now try to insert another character. You'll see that you can't.

**Comment by RobinHerbots** [comment] 2013-04-22 10:57
@lmiguelmh , 

That is because when you press end the caret moves to the end.  Repositioning the caret to a valid position renenables input.

**Comment by lmiguelmh** [comment] 2013-04-22 17:15
Did you try with property `placeholder: ""`? 
Press: [char] [char] [END] [HOME] [char] [END] [HOME] [char] ...

**Comment by RobinHerbots** [comment] 2013-04-23 12:34
@lmiguelmh ,

Now I see the problem!!  , ... I will fixed it asap.

Robin

**Comment by RobinHerbots** [comment] 2013-04-23 14:39
@lmiguelmh, 

Should be fixed in the latest version.  Can you have a try!

Robin

**Closed as completed** 2013-04-23 22:42 UTC
Labels: Main
