### ISSUE TITLE
Numeric inputs with default value are setted to blank when submit the form

### ISSUE THREAD

**Issue by garcia-jj** [RobinHerbots/Inputmask#983] opened 2015-07-27 06:18 UTC
I'm using this custom mask:

```
$.extend($.inputmask.defaults.aliases, {
    decimal: {
        alias: 'currency', 
        radixPoint: ",", 
        prefix: '', 
        groupSeparator: '', 
        removeMaskOnSubmit: false 
    } 
});
```

If the value in the input is `0,00`, when I submit the form the value is setted to blank value. Using firebug I see the values are sent as blank String instead of `0,00`.

**Comment by RobinHerbots** [comment] 2015-07-27 07:05
Duplicate of issue #786

**Closed as completed by RobinHerbots** 2015-07-27 07:05 UTC
Labels: Numerics

**Comment by garcia-jj** [comment] 2015-07-27 07:49
I don't know if issues are the same because in my case inputmask is set my input to blank when the value is 0.00 when submit the form. But the issue #786 is about visual value of input.

**Comment by RobinHerbots** [comment] 2015-07-27 08:14
@garcia-jj , 

The value 0.00 is removed because it's the same as the placeholder.  The inputmask does not differentiate  wheter the 0,00 is an entered value or just the placeholder.  Solving issue #786 will also solve your issue.

**Comment by RobinHerbots** [comment] 2015-07-27 12:52
@garcia-jj , 

Can you have a test with the latest version.

**Comment by garcia-jj** [comment] 2015-07-31 01:35
@RobinHerbots, thank you for your support. At this time with current unreleased version works fine. I'll waiting for a new release under CDN to update my projects.

Best regards.
