### ISSUE TITLE
Android Chrome Bug with radix Point

### ISSUE THREAD

**Issue by juanla** [RobinHerbots/Inputmask#1304] opened 2016-06-21 07:04 UTC
Hello, I have this fiddle not working in Android Chrome, works in firefox in Android and works in Desktop browsers too

https://jsfiddle.net/80m57hL2/9/

```
$( document ).ready(function() {
    $(".input-currency").inputmask('decimal', {
              radixPoint: ",",
                            autoGroup: true,
                            groupSeparator: ".",
                            groupSize: 3,
                            autoUnmask: true
        });
});
```

I cant insert commas using my Android device, point or comma keys don't make nothing when are  pressed. Any idea? Sorry my english. 

I noticed these error in 51.x version in Chrome mobile and I see it working in Chrome 47.x (I tested in iOS Chrome too)

**Comment by ntperdana** [comment] 2017-08-19 19:56
Hello...

I was wondering if this issue will be looked into anytime soon. We just deployed our Android App and we hit this bug. The inputmask does not work in Android. The behaviour can be best explained if you can open the fiddle from an Android device, you would see that typing a dot/comma would not appear at all.

Look forward to hearing from you.

Thanks.

**Comment by RobinHerbots** [comment] 2017-08-19 22:37
I will look into on monday.

**Comment by ntperdana** [comment] 2017-08-20 04:58
Hi Robert, 

Thanks very much in advance. Just to give you more information, if I open the jsfiddle in Android Chrome, here is what happens.

Scenario 1:
- Type 1: it displays "1"
- Type 2: it displays "12"
- Type 3: it displays "123"
- Type 4: it displays "1.234" -> the dot (.) is expected because of the GroupSeparator.
- Type 5: it displays "1,2345" -> it should be "12.345". By this time, entering (.) and (,) also does not work.
- Type 6: it displays "1,23456" -> it should be "123.456". By this time, entering (.) and (,) also does not work.
- and so on.

Scenario 2: 
- Type 1: it displays "1"
- Type (.) or (,):  it displays "1." or "1," respectively. To my understanding, (1,) should always be displayed becuase of RadixPoint. At least, this is what I get if I open the fiddle in desktop browsers. 
- Type 2: it displays "1,2" regardless (.) or (,) was typed previously. It should be expected because of RadixPoint.

Hopefully it gives you more information for troubleshooting and can get the root cause.

Look forward to hearing from you.

Thanks.

**Comment by RobinHerbots** [comment] 2017-08-21 08:09
@ntperdana , 

Can you retry with the latest version from github.

See https://jsfiddle.net/80m57hL2/14/

**Comment by ntperdana** [comment] 2017-08-21 14:13
Dear Robin,

Thanks for the update in advance.

Anyways, I have tried the fiddle again just now, it seems to work better but there is still a small glitch. 

**Scenario 1:**
- Type 1: it displays "1"
- Type 2: it displays "12"
- Type 3: it displays "123"
- Type 4: it displays "1.234" 
- Type 5: it displays "12.345"
- Type 6: it displays "123.456"
- Type 7: it displays "1.234.567"
- and so on..

**Scenario 2:**
- Type 1: it displays "1"
- Type 2: it displays "12"
- Type 3: it displays "123"
- Type 4: it displays "1.234" 
- Type 4: it displays "1,2344"
- Type 5: it displays "1,2345"
- Type 6: it displays "1,23456"
- and so on..

**Scenario 3:**
- Type 1: it displays "1"
- Type 2: it displays "12"
- Type 3: it displays "123"
- Type 4: it displays "1.234" 
- Type 3: it displays "12.343"
- Type 3: it displays "12,3433"
- Type 2: it displays "12,34332"
- and so on..

**Scenario 4:**
- Type 1: it displays "1"
- Type 2: it displays "12"
- Type 3: it displays "123"
- Type 4: it displays "1.234" 
- Type 3: it displays "12.343"
- Type 2: it displays "123.432"
- Type 2: it displays "123,4322"
- and so on..

**Scenario 5:**
- Type 1: it displays "1"
- Type 2: it displays "12"
- Type 3: it displays "123"
- Type 4: it displays "1.234" 
- Type 3: it displays "12.343"
- Type 2: it displays "123.432"
- Type 1: it displays "1.234.321"
- Type 1: it displays "12.343.211"
- Type 1: it displays "123.432.111"
- and so on..

Based on scenario 2-5, I can comment that if the number of digits is less than 6 and there is one number which repeats, it would trigger the comma to appear. But if the repetition occurs after the seventh digit, it will be just fine.

Hopefully You can pinpoint the issue soon.

Btw, if I want to start using the latest code which fix the problem, do I need to download the whole zip file again? Or I could just copy one of the files?

Thanks.

**Comment by RobinHerbots** [comment] 2017-08-21 14:34
@ntperdana , 

Thx for the feedback and examples.

With this https://jsfiddle.net/80m57hL2/15/ you can see the same behavior in a desktop browser as on android.  (inputEventOnly - This eases debugging)

How do you use the inputmask?  You include the bundle with a script tag?  If so you can grab the latest from the dist folder.

**Comment by ntperdana** [comment] 2017-08-21 14:42
Hi Robin,

I am not sure I understand you. Is the problem (dot changes to comma) to be expected? 

- https://jsfiddle.net/80m57hL2/15/ -> inputEventOnly
- https://jsfiddle.net/80m57hL2/14/ -> without inputEventOnly

Both fiddles produces the same problem in Android Chrome. However, I want the behaviour of the fiddle without inputEventOnly to work in Android as well. Hopefully you understand my concern here.

Look forward to hearing from you.

**Comment by RobinHerbots** [comment] 2017-08-21 14:52
@ntperdana , 

No the dot changes to coma is a bug!, but with the inputEventOnly option you can easily test the behavior on a desktop browser.

**Comment by ntperdana** [comment] 2017-08-21 15:02
Dear Robin,

Ah, ic ic...thanks for the tips then.

If that's the case,I will wait for your update then before deploying it to my app.

Thanks.

**Comment by ntperdana** [comment] 2017-08-22 12:50
Hi Robin,

Sorry to bother again, are you planning to look into the bug anytime soon this week?

Look forward to hearing from you.

**Comment by RobinHerbots** [comment] 2017-08-23 12:46
@ntperdana , 

There is an updated version.  Can you have a try.  

I still have 58 issues in the unittests failing for android, so make sure to test well on Android

**Comment by ntperdana** [comment] 2017-08-24 11:08
Hi Robert,

Just tried with version Version: 4.0.1-31. The behaviour is follows:

Type 1: it displays "1"
Type 2: it displays "12"
Type 3: it displays "123"
Type 4: it displays "1.234" -> but at this point, the cursor is placed between 3 and 4.

So, every four characters, it creates the group separates accordingly but it moves the cursor 1 character back.

**Comment by RobinHerbots** [comment] 2017-08-24 11:11
@ntperdana , 
Thx for the feedback I will look at it.

**Comment by RobinHerbots** [comment] 2017-08-24 11:16
@ntperdana , 

Did you tried with the jsfiddle?  https://jsfiddle.net/80m57hL2/15/

**Comment by ntperdana** [comment] 2017-08-24 11:45
Hi Robert,

Yup, just tried it now in the provider fiddle using Chrome on Android.

This email is sent from my mobile device. Please accept my sincere apology for any possible typos in this email.

Kind regards, 



Dana
Presales Manager | Presales Dvision
Mobile: +6282125686505| Email: novarica.perdana@mastersystem.co.id

**Comment by ntperdana** [comment] 2017-08-24 11:49
Hi Robert,

Yup, i just tried it now in the provided fiddle and the result is still the same as what I described above.


This email is sent from my mobile device. Please accept my sincere apology for any possible typos in this email.

Kind regards, 



Dana

**Comment by RobinHerbots** [comment] 2017-08-24 11:58
And with this? https://jsfiddle.net/80m57hL2/16/

**Comment by ntperdana** [comment] 2017-08-24 16:46
Hi Robert,

Nope, same result on Chrome Android. Still the same behaviour when the cursor is moved back 1 character.
 
Thanks.

Kind Regards,



Dana
+6282125686505
www.cloudbanget.com
Solusi Cloud Murah dan Handal, 
Cuma Di CloudBanget Tempatnya.

**Comment by RobinHerbots** [comment] 2017-08-25 06:59
Can you specify the version of Android and chrome. Can you also test the fiddle on a desktop.

**Comment by ntperdana** [comment] 2017-08-26 07:08
Ho Robin,

Chrome on Desktop does not have the problem.

My dev android device is Samsung Tab A6, Version 6.0.1. My chrome version is 59.0.3071.125.

Hope it helps.

Thanks.


This email is sent from my mobile device. Please accept my sincere apology for any possible typos in this email.

Kind regards, 



Dana

**Comment by RobinHerbots** [comment] 2019-11-29 11:21
@juanla , @ntperdana , 

I will close this issue.  Have a try with the latest beta of version 5

**Closed as completed by RobinHerbots** 2019-11-29 11:21 UTC
Labels: Android, Life example included => priority
