### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by anteksiler** [RobinHerbots/Inputmask#186] opened 2013-03-13 20:28 UTC
Have you guys tested it?

I tried it on a friend's phone, and the mask was not working.

**Comment by RobinHerbots** [comment] 2013-03-13 22:04
@anteksiler ,

I have tested it on android about a year ago and haven't tested again since then ;-)

I will verify the plugin an android soon as there are other issues opened for Android.

Can you specify the version of android, ... 

Robin

**Comment by espeiorin** [comment] 2013-03-20 20:24
@RobinHerbots I've tested on Android 4.2.2 and Android 2.3.4 in the default browser and in both inputmask doesn't work.

**Comment by RobinHerbots** [comment] 2013-03-20 22:28
@anteksiler , @xorna ,

Can you specify which mask you used to test.  I just did a quick try of the date-alias in the sdk android emulator.

Version 4.2.2 and it seems ok.

**Comment by RobinHerbots** [comment] 2013-03-20 22:38
hmm, ... when i use hardware keyboard present in the options it works, but if not and using the soft-keyboard, the caret positioning goes wrong, ... jumps to the last, ...  repositioning it to another position renables input

**Comment by espeiorin** [comment] 2013-03-21 12:45
@RobinHerbots Sorry, but you are right, the exception is the caret repositioning issue, but it's just an another Android annoyance, the mask is just working fine. I figured it out by removing some scripts that validate the values on keyup event. Many thanks

**Comment by espeiorin** [comment] 2013-03-21 13:13
@RobinHerbots funny, but it works only on Android 2.3 Galaxy Y, on Galaxy SIII and Galaxy Nexus, both with Android 4.2, the mask didn't work, I'm trying to get more information in tests here.

**Comment by RobinHerbots** [comment] 2013-03-21 13:18
Version 2.3, ... is handled by the plugin, ... and the ugly fix wasn't
needed for above, ... seems that the same issues comes back with some
android versions.

I need a reliable caretpositioning for android, ... has someone some more
documentation on this?  I will do some further testing in the emulators

btw entering about:debug to enable the extra options in the settings is
really helpfull, ... no need to adb & logcat

2013/3/21 André Gustavo Espeiorin notifications@github.com

**Comment by RobinHerbots** [comment] 2013-03-21 15:55
can someone have a quick test when replacing the caret fn in the inputmask with

```
 function caret(input, begin, end) {
            if (!$(input).is(':visible')) {
                return;
            }
            var npt = input.jquery && input.length > 0 ? input[0] : input, textRange;
            if (typeof begin == 'number') {
                end = (typeof end == 'number') ? end : begin;
                if (opts.insertMode == false && begin == end) end++; //set visualization for insert/overwrite mode
                if (npt.setSelectionRange) {
                    if (end == begin) {
                        npt.focus();
                        npt.setSelectionRange(begin, end);
                    } else {
                        npt.select();
                        npt.selectionStart = begin;
                        npt.selectionEnd = end;
                    }
                } else if (npt.createTextRange) {
                    textRange = npt.createTextRange();
                    textRange.moveStart('character', start);
                    end = end || start;
                    textRange.moveEnd('character', end);
                    textRange.select();
                }
                if (android && end != npt.selectionEnd) caretposCorrection = { begin: begin, end: end };
            } else {
                var caretpos = android ? caretposCorrection : null, caretposCorrection = null;
                if (caretpos == null) {
                    if (npt.setSelectionRange) {
                        begin = npt.selectionStart;
                        end = npt.selectionEnd;
                    } else if (document.selection && document.selection.createRange) {
                        var range = document.selection.createRange();
                        textRange = el.createTextRange();
                        textRange.setEndPoint("EndToStart", range);

                        begin = textRange.text.length;
                        end = begin + range.text.length;
                    }
                    caretpos = { begin: begin, end: end };
                }
                return caretpos;
            }
        };
```

**Comment by espeiorin** [comment] 2013-03-21 17:34
@RobinHerbots tested in Galaxy SIII and didn't work :/ I will keep trying

**Comment by Treyphor** [comment] 2013-03-21 23:56
I've tested some input masks on my nexus 7 version 4.2.2 using the chrome browser and the input masks appear to work, until you hit backspace. It appears to delete things but when you go to type something in again it puts all the deleted characters back.

**Comment by RobinHerbots** [comment] 2013-03-22 08:38
@Treyphor - thx for the feedback

@xorna ,

Can you have another try but put the code below in comments in jquery.inputmask.js

  if (android) {
                var browser = navigator.userAgent.match(/mobile safari.*/i);
                var version = parseInt(new RegExp(/[0-9]+/).exec(browser));
                android = version <= 533;
            }

**Comment by Treyphor** [comment] 2013-03-22 18:23
You're welcome. Have you seen that problem before? Any idea where I might start looking to try and fix it? Our company is finishing up a web app and we're hoping we don't have to remove the masking for android. It's like the mask doesn't update when the back button is pushed on android. I'm willing to help figure this out if you have things you want me to test or any ideas to try. Thanks! This plugin has been very useful for us. Nice work!

**Comment by Treyphor** [comment] 2013-03-22 18:42
Very strange.. I just tried an older version of the chrome android app and the masking appeared to work as it's supposed to. Updated to newest version and it's broken again. So I'm sure your stuff is working great and it's just something chrome is doing bad. Hopefully this one resolves itself, but in the mean time I'll be trying to find a workaround.

**Comment by Treyphor** [comment] 2013-03-22 19:26
I modified a fiddle to demonstrate the problem: http://jsfiddle.net/Qejuk/12/ It also doesn't reformat where the comma goes on backspace on android, which I see you fixed in another ticket for normal browsers so I think the problem is whatever google changed between browser versions has made it so the backspace button on their keyboard isn't firing the keydown, keyup, or whatever event you're using to cause the mask to update. Maybe I'll send a report over to google about it.

**Comment by RobinHerbots** [comment] 2013-03-22 19:26
I wrote an ungly patch for android 2.3.x  chrome browser version 533, but thought it wouldn't be needed on higher versions.

Can you retry with the latest version. (just committed).

The plugin should work only when deleting the last character the caret skips one position, but keeps working.  I will try to find a solution for that.  Caret positioning in Android is really not reliable.  Why can't they fix that?

**Comment by Treyphor** [comment] 2013-03-22 20:00
The issue still looks like it's there, but I only had a second to test it as I'm leaving work in a couple minutes. I'll have to look into it more next week. I'll probably try to hook it to my computer to do some remote debugging to find out what's going on. I'll keep you posted on what I find. I also submitted a bug report to google to see if they have anything to say about it (probably not).

Yea desktop chrome is awesome, hardly ever have issues with it. Trying to work with mobile chrome is a whole different story though. Thanks a bunch for looking into it!

**Comment by RobinHerbots** [comment] 2013-03-22 22:15
@Treyphor , @anteksiler , @xorna ,

I did some further testing in the emulator and figured out that the keydown event is not triggered when you set a selection where the begin and end isn't equal.  So as workaround, I make them always equal and that brings the inputmask alive in the emulator ;-)

I guess there should exist another fn to set the caret then setSelectionRange, selectionStart, selectionEnd, ...

anyway give the current latest a try!

**Comment by Treyphor** [comment] 2013-03-22 22:36
Awesome, I will test it first thing Monday when I get into work. Thank you for looking into it so quickly :)

**Comment by espeiorin** [comment] 2013-03-25 13:11
@RobinHerbots I updated here, but at Galaxy Nexus and Galaxy SIII (both Android 4.2) still not works. I'll teste more later.

**Comment by RobinHerbots** [comment] 2013-03-25 13:20
@xorna , 

Can you give me the mask you are testing on and also send me the useragent string you get from the Nexus and SIII

Best regards, 

Robin

**Comment by Treyphor** [comment] 2013-03-25 16:23
@RobinHerbots,

Just tested again on my Nexus 7. Looks like it's still not working.

useragent string from Nexus 7: "Mozilla/5.0 (Linux; Android 4.2.2; Nexus 7 Build/JDQ39) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.169 Safari/537.22"

Mask I'm testing with: 
$(this).inputmask("9999999", { "placeholder": " " }).on("keypress", function (e) {
        limitToNumbers(e);
      });

Let me know if there's anything you want me to test for you.

Thanks.

**Comment by RobinHerbots** [comment] 2013-03-25 16:33
@Treyphor,

Canyou do a little test.  Just replace in the jquery.inputmask.js the 534 with 537 (android version detection) and have a retry

Robin

**Comment by Treyphor** [comment] 2013-03-25 16:42
@RobinHerbots,

I changed it, cleared cache and everything and it's still doing the same thing. Maybe I changed it in the wrong place? I changed line 87 from: android534 = (533 < version <= 534); to: android534 = (533 < version <= 537);

I just put some breakpoints into the keydown, keyup, and keypress functions to see if anything happens when I press the back button. No break points are hit when I hit backspace, but keydown is hit on normal keys. Can we do anything if google has made their back button not fire any events?

**Comment by RobinHerbots** [comment] 2013-03-25 17:15
Maybe the input event?

**Comment by espeiorin** [comment] 2013-03-25 17:17
@RobinHerbots My masks:

$('#nocartao').inputmask({mask: "9999 9999 9999 9999", greedy : false, autoUnmask : true});
$('#mesvencimento').inputmask({mask: "99", greedy : false, autoUnmask : true});
$('#anovencimento').inputmask({mask: "99", greedy : false, autoUnmask : true});

User agents
Galaxy SIII
Mozilla/5.0 (Linux; U; Android 4.1.2; pt-br; GT-I9300 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

Galaxy Nexus
Mozilla/5.0 (Linux; U; Android 4.2.2; pt-br; Galaxy Nexus Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

**Comment by RobinHerbots** [comment] 2013-03-25 19:40
@Treyphor ,

So to summarize.  What is working and what is not. 

@xorna,

Why do you use the greedy option if you do not set a repeat?

**Comment by Treyphor** [comment] 2013-03-25 19:46
@RobinHerbots,

The input mask is working as long as I never hit backspace. As soon as I hit backspace things start to mess up. After all my testing I've been doing though I don't think it's a problem with your stuff. It's a problem with the android keyboard backspace button not firing any events, which I'm currently trying to work around. I'll let you know if I find anything. I don't know why google doesn't have their backspace fire any events. Very frustrating.

Looks like there's a lot of people having problems with chrome's keyboard not firing events. Here's a link where some people are having problems: https://code.google.com/p/chromium/issues/detail?id=118639 so for now i'm just going to say chrome for android is broken and hopefully they fix it soon. Thanks anyways for looking into it and trying to help me work around it.

I do not have the same problem with firefox on android... Come on chrome. But in firefox the caret randomly positions at the end of the input. I see what you mean about unreliable caret positioning in android. What a pain.

**Comment by espeiorin** [comment] 2013-03-25 19:59
@RobinHerbots you're right, I changed the masks and forgot to remove it. I'll test without greedy. Thanks

**Comment by RobinHerbots** [comment] 2013-03-31 23:14
@anteksiler @xorna @Treyphor 

Can someone give it another try with the latest version of the plugin.

Backspace should work correctly.

Robin

**Comment by Treyphor** [comment] 2013-04-01 16:01
It's still adding characters back after deleting them. I've worked around the problem I was having on android by creating new inputs with javascript on document ready for each input I need masked. Then I hide the original masked input and only show the javascript created one that isn't masked. This allows me to use input types to get the correct numeric keyboard to show up. Then when they blur out of the javascript created field I copy the value over to the hidden masked field. The main thing I wanted was to have the correct keyboard come up for numeric inputs, which doesn't work with the masks when you put an input type on there. This way the field still gets masked behind the scenes, and the correct numeric keyboard will show up. Just had to do a lot of special handling for each type of input to make sure they can't put in invalid characters. It's not pretty.. but it works for what I need. Still doesn't solve the problem of backspace on mobile chrome haha.

**Comment by RobinHerbots** [comment] 2013-04-01 22:20
Hmm, it worked well in the emulator on andrlid 4.2.2

Can someone donate some android devices to test with?

:)

**Comment by RobinHerbots** [comment] 2013-04-02 19:52
Can someone test the plugin on android 4.2.2  (real device - no emulator)

thx

**Comment by Treyphor** [comment] 2013-04-02 21:48
I got the version that says it was updated 2 days ago and still having the same problems. Also noticed the same problem in internet explorer 10 when you hit the little 'x' that microsoft decided to put in each text field. Hitting the 'x' erases the textbox contents, but when you type again it brings all the deleted stuff back.

**Comment by RobinHerbots** [comment] 2013-04-02 22:55
There is a new fix for android 2.3.x which should fix the backspace behavior.

Tested android 2.3.3, 3.0, 4.0, 4.2.1, 4.2.2 in the emulator and besides the damn keyboard who is switching all the time the backspace is working.

@Treyphor ,  can you create a new issue for IE10  (thx)

**Comment by RobinHerbots** [comment] 2013-04-18 19:42
I close this one, ... submit more specific issue for android,

**Closed as completed** 2013-11-06 10:23 UTC
Labels: Android

**Comment by Claudioneto** [comment] 2014-07-12 12:07
Hi, i have a problem too.

I am using Android 4.1.2 and Mozilla Firefox. My mask = $('#cpf').inputmask("999.999.999-99");

The mask appear, but not work correct.

**Comment by RobinHerbots** [comment] 2014-07-12 22:35
@Claudioneto , 

See #465
