### ISSUE TITLE
Problem with decimal mask and values less than 1

### ISSUE THREAD

**Issue by nicomdp** [RobinHerbots/Inputmask#263] opened 2013-06-17 14:26 UTC
I have problems with values like 0.12. When I type 0. te mask dissapear and I can't type any more digits.

This is my configuration:

$('#ID').inputmask('decimal', {'digits':2, radixPoint: '.', groupSeparator: ',', groupSize: 3, autoGroup: true, numericInput: false });

Thanks in advance.

**Comment by nicomdp** [comment] 2013-06-18 11:36
Here is the full code: 
http://jsfiddle.net/nicomdp/PwUDy/

**Comment by RobinHerbots** [comment] 2013-06-18 21:31
@nicomdp ,

The issue is fixed in the latest version.

You should remove the numericInput: false option from your mask.

Best regards, 

Robin

**Closed as completed by RobinHerbots** 2013-06-18 21:31 UTC

**Comment by nicomdp** [comment] 2013-06-18 21:52
Thanks man!
