### ISSUE TITLE
numeric alias produces "0.00" instead of null when cleared out.

### ISSUE THREAD

**Issue by kjavia** [RobinHerbots/Inputmask#902] opened 2015-04-30 17:19 UTC
I am evaluating this excellent plugin. When I clear an input field, it sets it to "0.00" instead of null. This maybe a known issue to you but would put it out here.

Am I missing something? 

``` javascript
  var options = {
          alias: 'numeric',
          autoGroup: scope.autoGroup || true,
          autoUnmask: true,
          radixPoint: scope.decimalChar || '.',
          digits: scope.numOfDecimals > -1 ? scope.numOfDecimals : 2,
          digitsOptional: typeof scope.digitsOptional !== 'undefined' ?
                                            scope.digitsOptional : true,
          groupSeparator: scope.groupSeparator || ',',
          prefix: scope.prefix || '',
          placeholder: scope.placeholder || '0',
          suffix: scope.suffix || '',
          unmaskAsNumber: true
        };

        elem.inputmask(options); // apply the jquery input mask plugin
```

**Comment by RobinHerbots** [comment] 2015-05-04 12:16
duplicate of #786

**Comment by kjavia** [comment] 2015-05-04 20:55
@RobinHerbots  thanks for addressing this.

**Comment by kjavia** [comment] 2015-11-10 19:09
@RobinHerbots I started working with 3.2.3 and still see the problem. There is no way for me to clear the input once it has a focus. It defaults to 0 or 0.00 etc. What options need to be passed so it can be cleared completely (input value should be null or empty string)?

Edit: To clarify, if the textbox gets focus and then the user tabs out of it, the value remains as "0". But if the user enters a value and uses delete/backspace to clear it then the value becomes "" after focus has been lost. So I think the problem remains if there is no entry done on the input.

**Comment by RobinHerbots** [comment] 2016-03-11 10:04
@kjavia , 

Can you retest with the latest version on github.

**Closed as completed** 2016-03-14 14:15 UTC
Labels: Numerics
